apiVersion: v1
kind: Secret
metadata:
  name: mariadb-secret
  namespace: ddts-dev
  labels:
    app: mariadb
    environment: dev
type: Opaque
data:
  # echo -n 'dev12345678' | base64
  MARIADB_ROOT_PASSWORD: ZGV2MTIzNDU2Nzg=
