apiVersion: v1
kind: Secret
metadata:
  name: app-secret
  namespace: ddts-dev
  labels:
    app: ddts-app
    environment: dev
type: Opaque
data:
  # echo -n 'dev12345678' | base64
  SPRING_DATASOURCE_MASTER_PASSWORD: ZGV2MTIzNDU2Nzg=
  SPRING_DATASOURCE_SLAVE1_PASSWORD: ZGV2MTIzNDU2Nzg=
