spring:
  profiles:
    # Spring 的 Profile 机制是为了隔离不同环境中的配置，参考：https://docs.spring.io/spring-boot/docs/2.6.2/reference/html/features.html#features.profiles
    # active: "@active-profile@"
    active: test

# 日志配置文件位置，默认的时候使用最严厉的 online配置，而不是松散的 offline 配置
logging:
  config: classpath:log4j2/log4j2-online.xml

common:
  # 对外开放的服务端口
  servicePort: 8411
  # 交易分布式锁的默认时长，单位为秒
  lockExpiration: 10
  mockMode: false

endpoints:
  sensitive: false
  docs:
    enabled: true
---
spring:
  config:
    activate:
      on-profile: local

common:
  env: test

# 日志配置文件位置
logging:
  # todo：记得加入软链接配置
  config: classpath:log4j2/log4j2-offline.xml
  # 只有线下的配置才可以在 logging 配置里面打印 debug 的 mybatis 的 sql 日志
  level.mapperpackagepath: debug # 打印mybatis的sql日志
---
spring:
  config:
    activate:
      on-profile: dev
common:
  env: dev

# 日志配置文件位置
logging:
  config: classpath:log4j2/log4j2-offline.xml
  level.mapperpackagepath: debug # 打印mybatis的sql日志
---
spring:
  config:
    activate:
      # 不要漏掉空格，不然会报：Reason: org.springframework.core.convert.ConverterNotFoundException: No converter found capable of converting from type [java.lang.String] to type [org.springframework.boot.context.config.ConfigDataProperties$Activate]
      on-profile: test
  datasource:
    # 纯内存的 db 如下
    url: jdbc:h2:file:/data/demo
    username: sa
    password: password
    driverClassName: org.h2.Driver
  jpa:
    spring.jpa.database-platform: org.hibernate.dialect.H2Dialect

common:
  env: test
  # mockMode: true

# 日志配置文件位置
logging:
  config: classpath:log4j2/log4j2-offline.xml
  level.mapperpackagepath: debug # 打印mybatis的sql日志
---
spring:
  # 替代配置
  # profiles:
  config:
    activate:
      on-profile: staging
common:
  env: staging
---
spring:
  config:
    activate:
      on-profile: prod
common:
  env: prod
