apiVersion: v1
kind: ConfigMap
metadata:
  name: app-config
  namespace: ddts-staging
  labels:
    app: ddts-app
    environment: staging
data:
  SPRING_PROFILES_ACTIVE: "staging"
  SPRING_DATASOURCE_MASTER_JDBC_URL: "jdbc:mysql://mariadb-svc:3306/test_master?characterEncoding=utf-8&serverTimezone=Asia/Shanghai&useSSL=false&autoReconnect=false&failOverReadOnly=false&zeroDateTimeBehavior=convertToNull&useAffectedRows=true&allowMultiQueries=true&socketTimeout=10000&rewriteBatchedStatements=true&useCompression=true&connectTimeout=5000&maxRows=0&useUnicode=true&useDynamicCharsetInfo=false"
  SPRING_DATASOURCE_MASTER_DRIVER_CLASS_NAME: "com.mysql.cj.jdbc.Driver"
  SPRING_DATASOURCE_MASTER_USERNAME: "root"
  SPRING_DATASOURCE_MASTER_POOL_NAME: "master-pool"
  SPRING_DATASOURCE_SLAVE1_JDBC_URL: "jdbc:mysql://mariadb-svc:3306/test_slave1?characterEncoding=utf-8&serverTimezone=Asia/Shanghai&useSSL=false&autoReconnect=false&failOverReadOnly=false&zeroDateTimeBehavior=convertToNull&useAffectedRows=true&allowMultiQueries=true&socketTimeout=10000&rewriteBatchedStatements=true&useCompression=true&connectTimeout=5000&maxRows=0&useUnicode=true&useDynamicCharsetInfo=false"
  SPRING_DATASOURCE_SLAVE1_DRIVER_CLASS_NAME: "com.mysql.cj.jdbc.Driver"
  SPRING_DATASOURCE_SLAVE1_USERNAME: "root"
  SPRING_DATASOURCE_SLAVE1_POOL_NAME: "slave-pool"
  COMMON_ENV: "staging"
  LOGGING_CONFIG: "classpath:log4j2/log4j2-online.xml"
  JAVA_OPTS: "-Xms512m -Xmx1g"
