package com.magicliang.transaction.sys.common.dal.mybatis.mapper;

import com.magicliang.transaction.sys.common.dal.mybatis.po.TransAlipaySubOrderPo;
import com.magicliang.transaction.sys.common.dal.mybatis.po.TransAlipaySubOrderPoExample;
import org.apache.ibatis.annotations.*;
import org.apache.ibatis.type.JdbcType;

import java.util.List;

public interface TransAlipaySubOrderPoMapper {
    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table tb_trans_alipay_suborder
     *
     * @mbg.generated Wed Jan 26 17:49:11 CST 2022
     */
    @SelectProvider(type = TransAlipaySubOrderPoSqlProvider.class, method = "countByExample")
    long countByExample(TransAlipaySubOrderPoExample example);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table tb_trans_alipay_suborder
     *
     * @mbg.generated Wed Jan 26 17:49:11 CST 2022
     */
    @DeleteProvider(type = TransAlipaySubOrderPoSqlProvider.class, method = "deleteByExample")
    int deleteByExample(TransAlipaySubOrderPoExample example);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table tb_trans_alipay_suborder
     *
     * @mbg.generated Wed Jan 26 17:49:11 CST 2022
     */
    @Delete({
            "delete from tb_trans_alipay_suborder",
            "where id = #{id,jdbcType=BIGINT}"
    })
    int deleteByPrimaryKey(Long id);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table tb_trans_alipay_suborder
     *
     * @mbg.generated Wed Jan 26 17:49:11 CST 2022
     */
    @Insert({
            "insert into tb_trans_alipay_suborder (gmt_created, gmt_modified, ",
            "pay_order_no, to_account_no, ",
            "name)",
            "values (#{gmtCreated,jdbcType=TIMESTAMP}, #{gmtModified,jdbcType=TIMESTAMP}, ",
            "#{payOrderNo,jdbcType=BIGINT}, #{toAccountNo,jdbcType=VARCHAR}, ",
            "#{name,jdbcType=VARCHAR})"
    })
    @SelectKey(statement = "SELECT LAST_INSERT_ID()", keyProperty = "id", before = false, resultType = Long.class)
    int insert(TransAlipaySubOrderPo record);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table tb_trans_alipay_suborder
     *
     * @mbg.generated Wed Jan 26 17:49:11 CST 2022
     */
    @InsertProvider(type = TransAlipaySubOrderPoSqlProvider.class, method = "insertSelective")
    @SelectKey(statement = "SELECT LAST_INSERT_ID()", keyProperty = "id", before = false, resultType = Long.class)
    int insertSelective(TransAlipaySubOrderPo record);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table tb_trans_alipay_suborder
     *
     * @mbg.generated Wed Jan 26 17:49:11 CST 2022
     */
    @SelectProvider(type = TransAlipaySubOrderPoSqlProvider.class, method = "selectByExample")
    @Results({
            @Result(column = "id", property = "id", jdbcType = JdbcType.BIGINT, id = true),
            @Result(column = "gmt_created", property = "gmtCreated", jdbcType = JdbcType.TIMESTAMP),
            @Result(column = "gmt_modified", property = "gmtModified", jdbcType = JdbcType.TIMESTAMP),
            @Result(column = "pay_order_no", property = "payOrderNo", jdbcType = JdbcType.BIGINT),
            @Result(column = "to_account_no", property = "toAccountNo", jdbcType = JdbcType.VARCHAR),
            @Result(column = "name", property = "name", jdbcType = JdbcType.VARCHAR)
    })
    List<TransAlipaySubOrderPo> selectByExample(TransAlipaySubOrderPoExample example);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table tb_trans_alipay_suborder
     *
     * @mbg.generated Wed Jan 26 17:49:11 CST 2022
     */
    @Select({
            "select",
            "id, gmt_created, gmt_modified, pay_order_no, to_account_no, name",
            "from tb_trans_alipay_suborder",
            "where id = #{id,jdbcType=BIGINT}"
    })
    @Results({
            @Result(column = "id", property = "id", jdbcType = JdbcType.BIGINT, id = true),
            @Result(column = "gmt_created", property = "gmtCreated", jdbcType = JdbcType.TIMESTAMP),
            @Result(column = "gmt_modified", property = "gmtModified", jdbcType = JdbcType.TIMESTAMP),
            @Result(column = "pay_order_no", property = "payOrderNo", jdbcType = JdbcType.BIGINT),
            @Result(column = "to_account_no", property = "toAccountNo", jdbcType = JdbcType.VARCHAR),
            @Result(column = "name", property = "name", jdbcType = JdbcType.VARCHAR)
    })
    TransAlipaySubOrderPo selectByPrimaryKey(Long id);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table tb_trans_alipay_suborder
     *
     * @mbg.generated Wed Jan 26 17:49:11 CST 2022
     */
    @UpdateProvider(type = TransAlipaySubOrderPoSqlProvider.class, method = "updateByExampleSelective")
    int updateByExampleSelective(@Param("record") TransAlipaySubOrderPo record, @Param("example") TransAlipaySubOrderPoExample example);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table tb_trans_alipay_suborder
     *
     * @mbg.generated Wed Jan 26 17:49:11 CST 2022
     */
    @UpdateProvider(type = TransAlipaySubOrderPoSqlProvider.class, method = "updateByExample")
    int updateByExample(@Param("record") TransAlipaySubOrderPo record, @Param("example") TransAlipaySubOrderPoExample example);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table tb_trans_alipay_suborder
     *
     * @mbg.generated Wed Jan 26 17:49:11 CST 2022
     */
    @UpdateProvider(type = TransAlipaySubOrderPoSqlProvider.class, method = "updateByPrimaryKeySelective")
    int updateByPrimaryKeySelective(TransAlipaySubOrderPo record);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table tb_trans_alipay_suborder
     *
     * @mbg.generated Wed Jan 26 17:49:11 CST 2022
     */
    @Update({
            "update tb_trans_alipay_suborder",
            "set gmt_created = #{gmtCreated,jdbcType=TIMESTAMP},",
            "gmt_modified = #{gmtModified,jdbcType=TIMESTAMP},",
            "pay_order_no = #{payOrderNo,jdbcType=BIGINT},",
            "to_account_no = #{toAccountNo,jdbcType=VARCHAR},",
            "name = #{name,jdbcType=VARCHAR}",
            "where id = #{id,jdbcType=BIGINT}"
    })
    int updateByPrimaryKey(TransAlipaySubOrderPo record);
}