package com.magicliang.transaction.sys.common.dal.mybatis.mapper;

import com.magicliang.transaction.sys.common.dal.mybatis.po.TransPayOrderPo;
import com.magicliang.transaction.sys.common.dal.mybatis.po.TransPayOrderPoExample;
import com.magicliang.transaction.sys.common.dal.mybatis.po.TransPayOrderPoExample.Criteria;
import com.magicliang.transaction.sys.common.dal.mybatis.po.TransPayOrderPoExample.Criterion;
import org.apache.ibatis.jdbc.SQL;

import java.util.List;
import java.util.Map;

public class TransPayOrderPoSqlProvider {
    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table tb_trans_pay_order
     *
     * @mbg.generated Wed Jan 26 17:49:11 CST 2022
     */
    public String countByExample(TransPayOrderPoExample example) {
        SQL sql = new SQL();
        sql.SELECT("count(*)").FROM("tb_trans_pay_order");
        applyWhere(sql, example, false);
        return sql.toString();
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table tb_trans_pay_order
     *
     * @mbg.generated Wed Jan 26 17:49:11 CST 2022
     */
    public String deleteByExample(TransPayOrderPoExample example) {
        SQL sql = new SQL();
        sql.DELETE_FROM("tb_trans_pay_order");
        applyWhere(sql, example, false);
        return sql.toString();
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table tb_trans_pay_order
     *
     * @mbg.generated Wed Jan 26 17:49:11 CST 2022
     */
    public String insertSelective(TransPayOrderPo record) {
        SQL sql = new SQL();
        sql.INSERT_INTO("tb_trans_pay_order");

        if (record.getGmtCreated() != null) {
            sql.VALUES("gmt_created", "#{gmtCreated,jdbcType=TIMESTAMP}");
        }

        if (record.getGmtModified() != null) {
            sql.VALUES("gmt_modified", "#{gmtModified,jdbcType=TIMESTAMP}");
        }

        if (record.getPayOrderNo() != null) {
            sql.VALUES("pay_order_no", "#{payOrderNo,jdbcType=BIGINT}");
        }

        if (record.getSysCode() != null) {
            sql.VALUES("sys_code", "#{sysCode,jdbcType=VARCHAR}");
        }

        if (record.getBizIdentifyNo() != null) {
            sql.VALUES("biz_identify_no", "#{bizIdentifyNo,jdbcType=VARCHAR}");
        }

        if (record.getBizUniqueNo() != null) {
            sql.VALUES("biz_unique_no", "#{bizUniqueNo,jdbcType=VARCHAR}");
        }

        if (record.getMoney() != null) {
            sql.VALUES("money", "#{money,jdbcType=BIGINT}");
        }

        if (record.getPayChannelType() != null) {
            sql.VALUES("pay_channel_type", "#{payChannelType,jdbcType=INTEGER}");
        }

        if (record.getTargetAccountType() != null) {
            sql.VALUES("target_account_type", "#{targetAccountType,jdbcType=INTEGER}");
        }

        if (record.getAccountingEntry() != null) {
            sql.VALUES("accounting_entry", "#{accountingEntry,jdbcType=INTEGER}");
        }

        if (record.getGmtAcceptedTime() != null) {
            sql.VALUES("gmt_accepted_time", "#{gmtAcceptedTime,jdbcType=TIMESTAMP}");
        }

        if (record.getGmtPaymentBeginTime() != null) {
            sql.VALUES("gmt_payment_begin_time", "#{gmtPaymentBeginTime,jdbcType=TIMESTAMP}");
        }

        if (record.getGmtPaymentSuccessTime() != null) {
            sql.VALUES("gmt_payment_success_time", "#{gmtPaymentSuccessTime,jdbcType=TIMESTAMP}");
        }

        if (record.getGmtPaymentFailureTime() != null) {
            sql.VALUES("gmt_payment_failure_time", "#{gmtPaymentFailureTime,jdbcType=TIMESTAMP}");
        }

        if (record.getGmtPaymentClosedTime() != null) {
            sql.VALUES("gmt_payment_closed_time", "#{gmtPaymentClosedTime,jdbcType=TIMESTAMP}");
        }

        if (record.getGmtPaymentBouncedTime() != null) {
            sql.VALUES("gmt_payment_bounced_time", "#{gmtPaymentBouncedTime,jdbcType=TIMESTAMP}");
        }

        if (record.getStatus() != null) {
            sql.VALUES("status", "#{status,jdbcType=INTEGER}");
        }

        if (record.getVersion() != null) {
            sql.VALUES("version", "#{version,jdbcType=INTEGER}");
        }

        if (record.getMemo() != null) {
            sql.VALUES("memo", "#{memo,jdbcType=VARCHAR}");
        }

        if (record.getChannelPaymentTraceNo() != null) {
            sql.VALUES("channel_payment_trace_no", "#{channelPaymentTraceNo,jdbcType=VARCHAR}");
        }

        if (record.getChannelDishonorTraceNo() != null) {
            sql.VALUES("channel_dishonor_trace_no", "#{channelDishonorTraceNo,jdbcType=VARCHAR}");
        }

        if (record.getChannelErrorCode() != null) {
            sql.VALUES("channel_error_code", "#{channelErrorCode,jdbcType=VARCHAR}");
        }

        if (record.getBusinessEntity() != null) {
            sql.VALUES("business_entity", "#{businessEntity,jdbcType=VARCHAR}");
        }

        if (record.getNotifyUri() != null) {
            sql.VALUES("notify_uri", "#{notifyUri,jdbcType=VARCHAR}");
        }

        if (record.getExtendInfo() != null) {
            sql.VALUES("extend_info", "#{extendInfo,jdbcType=VARCHAR}");
        }

        if (record.getBizInfo() != null) {
            sql.VALUES("biz_info", "#{bizInfo,jdbcType=VARCHAR}");
        }

        if (record.getEnv() != null) {
            sql.VALUES("env", "#{env,jdbcType=INTEGER}");
        }

        return sql.toString();
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table tb_trans_pay_order
     *
     * @mbg.generated Wed Jan 26 17:49:11 CST 2022
     */
    public String selectByExample(TransPayOrderPoExample example) {
        SQL sql = new SQL();
        if (example != null && example.isDistinct()) {
            sql.SELECT_DISTINCT("id");
        } else {
            sql.SELECT("id");
        }
        sql.SELECT("gmt_created");
        sql.SELECT("gmt_modified");
        sql.SELECT("pay_order_no");
        sql.SELECT("sys_code");
        sql.SELECT("biz_identify_no");
        sql.SELECT("biz_unique_no");
        sql.SELECT("money");
        sql.SELECT("pay_channel_type");
        sql.SELECT("target_account_type");
        sql.SELECT("accounting_entry");
        sql.SELECT("gmt_accepted_time");
        sql.SELECT("gmt_payment_begin_time");
        sql.SELECT("gmt_payment_success_time");
        sql.SELECT("gmt_payment_failure_time");
        sql.SELECT("gmt_payment_closed_time");
        sql.SELECT("gmt_payment_bounced_time");
        sql.SELECT("status");
        sql.SELECT("version");
        sql.SELECT("memo");
        sql.SELECT("channel_payment_trace_no");
        sql.SELECT("channel_dishonor_trace_no");
        sql.SELECT("channel_error_code");
        sql.SELECT("business_entity");
        sql.SELECT("notify_uri");
        sql.SELECT("extend_info");
        sql.SELECT("biz_info");
        sql.SELECT("env");
        sql.FROM("tb_trans_pay_order");
        applyWhere(sql, example, false);

        if (example != null && example.getOrderByClause() != null) {
            sql.ORDER_BY(example.getOrderByClause());
        }

        return sql.toString();
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table tb_trans_pay_order
     *
     * @mbg.generated Wed Jan 26 17:49:11 CST 2022
     */
    public String updateByExampleSelective(Map<String, Object> parameter) {
        TransPayOrderPo record = (TransPayOrderPo) parameter.get("record");
        TransPayOrderPoExample example = (TransPayOrderPoExample) parameter.get("example");

        SQL sql = new SQL();
        sql.UPDATE("tb_trans_pay_order");

        if (record.getId() != null) {
            sql.SET("id = #{record.id,jdbcType=BIGINT}");
        }

        if (record.getGmtCreated() != null) {
            sql.SET("gmt_created = #{record.gmtCreated,jdbcType=TIMESTAMP}");
        }

        if (record.getGmtModified() != null) {
            sql.SET("gmt_modified = #{record.gmtModified,jdbcType=TIMESTAMP}");
        }

        if (record.getPayOrderNo() != null) {
            sql.SET("pay_order_no = #{record.payOrderNo,jdbcType=BIGINT}");
        }

        if (record.getSysCode() != null) {
            sql.SET("sys_code = #{record.sysCode,jdbcType=VARCHAR}");
        }

        if (record.getBizIdentifyNo() != null) {
            sql.SET("biz_identify_no = #{record.bizIdentifyNo,jdbcType=VARCHAR}");
        }

        if (record.getBizUniqueNo() != null) {
            sql.SET("biz_unique_no = #{record.bizUniqueNo,jdbcType=VARCHAR}");
        }

        if (record.getMoney() != null) {
            sql.SET("money = #{record.money,jdbcType=BIGINT}");
        }

        if (record.getPayChannelType() != null) {
            sql.SET("pay_channel_type = #{record.payChannelType,jdbcType=INTEGER}");
        }

        if (record.getTargetAccountType() != null) {
            sql.SET("target_account_type = #{record.targetAccountType,jdbcType=INTEGER}");
        }

        if (record.getAccountingEntry() != null) {
            sql.SET("accounting_entry = #{record.accountingEntry,jdbcType=INTEGER}");
        }

        if (record.getGmtAcceptedTime() != null) {
            sql.SET("gmt_accepted_time = #{record.gmtAcceptedTime,jdbcType=TIMESTAMP}");
        }

        if (record.getGmtPaymentBeginTime() != null) {
            sql.SET("gmt_payment_begin_time = #{record.gmtPaymentBeginTime,jdbcType=TIMESTAMP}");
        }

        if (record.getGmtPaymentSuccessTime() != null) {
            sql.SET("gmt_payment_success_time = #{record.gmtPaymentSuccessTime,jdbcType=TIMESTAMP}");
        }

        if (record.getGmtPaymentFailureTime() != null) {
            sql.SET("gmt_payment_failure_time = #{record.gmtPaymentFailureTime,jdbcType=TIMESTAMP}");
        }

        if (record.getGmtPaymentClosedTime() != null) {
            sql.SET("gmt_payment_closed_time = #{record.gmtPaymentClosedTime,jdbcType=TIMESTAMP}");
        }

        if (record.getGmtPaymentBouncedTime() != null) {
            sql.SET("gmt_payment_bounced_time = #{record.gmtPaymentBouncedTime,jdbcType=TIMESTAMP}");
        }

        if (record.getStatus() != null) {
            sql.SET("status = #{record.status,jdbcType=INTEGER}");
        }

        if (record.getVersion() != null) {
            sql.SET("version = #{record.version,jdbcType=INTEGER}");
        }

        if (record.getMemo() != null) {
            sql.SET("memo = #{record.memo,jdbcType=VARCHAR}");
        }

        if (record.getChannelPaymentTraceNo() != null) {
            sql.SET("channel_payment_trace_no = #{record.channelPaymentTraceNo,jdbcType=VARCHAR}");
        }

        if (record.getChannelDishonorTraceNo() != null) {
            sql.SET("channel_dishonor_trace_no = #{record.channelDishonorTraceNo,jdbcType=VARCHAR}");
        }

        if (record.getChannelErrorCode() != null) {
            sql.SET("channel_error_code = #{record.channelErrorCode,jdbcType=VARCHAR}");
        }

        if (record.getBusinessEntity() != null) {
            sql.SET("business_entity = #{record.businessEntity,jdbcType=VARCHAR}");
        }

        if (record.getNotifyUri() != null) {
            sql.SET("notify_uri = #{record.notifyUri,jdbcType=VARCHAR}");
        }

        if (record.getExtendInfo() != null) {
            sql.SET("extend_info = #{record.extendInfo,jdbcType=VARCHAR}");
        }

        if (record.getBizInfo() != null) {
            sql.SET("biz_info = #{record.bizInfo,jdbcType=VARCHAR}");
        }

        if (record.getEnv() != null) {
            sql.SET("env = #{record.env,jdbcType=INTEGER}");
        }

        applyWhere(sql, example, true);
        return sql.toString();
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table tb_trans_pay_order
     *
     * @mbg.generated Wed Jan 26 17:49:11 CST 2022
     */
    public String updateByExample(Map<String, Object> parameter) {
        SQL sql = new SQL();
        sql.UPDATE("tb_trans_pay_order");

        sql.SET("id = #{record.id,jdbcType=BIGINT}");
        sql.SET("gmt_created = #{record.gmtCreated,jdbcType=TIMESTAMP}");
        sql.SET("gmt_modified = #{record.gmtModified,jdbcType=TIMESTAMP}");
        sql.SET("pay_order_no = #{record.payOrderNo,jdbcType=BIGINT}");
        sql.SET("sys_code = #{record.sysCode,jdbcType=VARCHAR}");
        sql.SET("biz_identify_no = #{record.bizIdentifyNo,jdbcType=VARCHAR}");
        sql.SET("biz_unique_no = #{record.bizUniqueNo,jdbcType=VARCHAR}");
        sql.SET("money = #{record.money,jdbcType=BIGINT}");
        sql.SET("pay_channel_type = #{record.payChannelType,jdbcType=INTEGER}");
        sql.SET("target_account_type = #{record.targetAccountType,jdbcType=INTEGER}");
        sql.SET("accounting_entry = #{record.accountingEntry,jdbcType=INTEGER}");
        sql.SET("gmt_accepted_time = #{record.gmtAcceptedTime,jdbcType=TIMESTAMP}");
        sql.SET("gmt_payment_begin_time = #{record.gmtPaymentBeginTime,jdbcType=TIMESTAMP}");
        sql.SET("gmt_payment_success_time = #{record.gmtPaymentSuccessTime,jdbcType=TIMESTAMP}");
        sql.SET("gmt_payment_failure_time = #{record.gmtPaymentFailureTime,jdbcType=TIMESTAMP}");
        sql.SET("gmt_payment_closed_time = #{record.gmtPaymentClosedTime,jdbcType=TIMESTAMP}");
        sql.SET("gmt_payment_bounced_time = #{record.gmtPaymentBouncedTime,jdbcType=TIMESTAMP}");
        sql.SET("status = #{record.status,jdbcType=INTEGER}");
        sql.SET("version = #{record.version,jdbcType=INTEGER}");
        sql.SET("memo = #{record.memo,jdbcType=VARCHAR}");
        sql.SET("channel_payment_trace_no = #{record.channelPaymentTraceNo,jdbcType=VARCHAR}");
        sql.SET("channel_dishonor_trace_no = #{record.channelDishonorTraceNo,jdbcType=VARCHAR}");
        sql.SET("channel_error_code = #{record.channelErrorCode,jdbcType=VARCHAR}");
        sql.SET("business_entity = #{record.businessEntity,jdbcType=VARCHAR}");
        sql.SET("notify_uri = #{record.notifyUri,jdbcType=VARCHAR}");
        sql.SET("extend_info = #{record.extendInfo,jdbcType=VARCHAR}");
        sql.SET("biz_info = #{record.bizInfo,jdbcType=VARCHAR}");
        sql.SET("env = #{record.env,jdbcType=INTEGER}");

        TransPayOrderPoExample example = (TransPayOrderPoExample) parameter.get("example");
        applyWhere(sql, example, true);
        return sql.toString();
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table tb_trans_pay_order
     *
     * @mbg.generated Wed Jan 26 17:49:11 CST 2022
     */
    public String updateByPrimaryKeySelective(TransPayOrderPo record) {
        SQL sql = new SQL();
        sql.UPDATE("tb_trans_pay_order");

        if (record.getGmtCreated() != null) {
            sql.SET("gmt_created = #{gmtCreated,jdbcType=TIMESTAMP}");
        }

        if (record.getGmtModified() != null) {
            sql.SET("gmt_modified = #{gmtModified,jdbcType=TIMESTAMP}");
        }

        if (record.getPayOrderNo() != null) {
            sql.SET("pay_order_no = #{payOrderNo,jdbcType=BIGINT}");
        }

        if (record.getSysCode() != null) {
            sql.SET("sys_code = #{sysCode,jdbcType=VARCHAR}");
        }

        if (record.getBizIdentifyNo() != null) {
            sql.SET("biz_identify_no = #{bizIdentifyNo,jdbcType=VARCHAR}");
        }

        if (record.getBizUniqueNo() != null) {
            sql.SET("biz_unique_no = #{bizUniqueNo,jdbcType=VARCHAR}");
        }

        if (record.getMoney() != null) {
            sql.SET("money = #{money,jdbcType=BIGINT}");
        }

        if (record.getPayChannelType() != null) {
            sql.SET("pay_channel_type = #{payChannelType,jdbcType=INTEGER}");
        }

        if (record.getTargetAccountType() != null) {
            sql.SET("target_account_type = #{targetAccountType,jdbcType=INTEGER}");
        }

        if (record.getAccountingEntry() != null) {
            sql.SET("accounting_entry = #{accountingEntry,jdbcType=INTEGER}");
        }

        if (record.getGmtAcceptedTime() != null) {
            sql.SET("gmt_accepted_time = #{gmtAcceptedTime,jdbcType=TIMESTAMP}");
        }

        if (record.getGmtPaymentBeginTime() != null) {
            sql.SET("gmt_payment_begin_time = #{gmtPaymentBeginTime,jdbcType=TIMESTAMP}");
        }

        if (record.getGmtPaymentSuccessTime() != null) {
            sql.SET("gmt_payment_success_time = #{gmtPaymentSuccessTime,jdbcType=TIMESTAMP}");
        }

        if (record.getGmtPaymentFailureTime() != null) {
            sql.SET("gmt_payment_failure_time = #{gmtPaymentFailureTime,jdbcType=TIMESTAMP}");
        }

        if (record.getGmtPaymentClosedTime() != null) {
            sql.SET("gmt_payment_closed_time = #{gmtPaymentClosedTime,jdbcType=TIMESTAMP}");
        }

        if (record.getGmtPaymentBouncedTime() != null) {
            sql.SET("gmt_payment_bounced_time = #{gmtPaymentBouncedTime,jdbcType=TIMESTAMP}");
        }

        if (record.getStatus() != null) {
            sql.SET("status = #{status,jdbcType=INTEGER}");
        }

        if (record.getVersion() != null) {
            sql.SET("version = #{version,jdbcType=INTEGER}");
        }

        if (record.getMemo() != null) {
            sql.SET("memo = #{memo,jdbcType=VARCHAR}");
        }

        if (record.getChannelPaymentTraceNo() != null) {
            sql.SET("channel_payment_trace_no = #{channelPaymentTraceNo,jdbcType=VARCHAR}");
        }

        if (record.getChannelDishonorTraceNo() != null) {
            sql.SET("channel_dishonor_trace_no = #{channelDishonorTraceNo,jdbcType=VARCHAR}");
        }

        if (record.getChannelErrorCode() != null) {
            sql.SET("channel_error_code = #{channelErrorCode,jdbcType=VARCHAR}");
        }

        if (record.getBusinessEntity() != null) {
            sql.SET("business_entity = #{businessEntity,jdbcType=VARCHAR}");
        }

        if (record.getNotifyUri() != null) {
            sql.SET("notify_uri = #{notifyUri,jdbcType=VARCHAR}");
        }

        if (record.getExtendInfo() != null) {
            sql.SET("extend_info = #{extendInfo,jdbcType=VARCHAR}");
        }

        if (record.getBizInfo() != null) {
            sql.SET("biz_info = #{bizInfo,jdbcType=VARCHAR}");
        }

        if (record.getEnv() != null) {
            sql.SET("env = #{env,jdbcType=INTEGER}");
        }

        sql.WHERE("id = #{id,jdbcType=BIGINT}");

        return sql.toString();
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table tb_trans_pay_order
     *
     * @mbg.generated Wed Jan 26 17:49:11 CST 2022
     */
    protected void applyWhere(SQL sql, TransPayOrderPoExample example, boolean includeExamplePhrase) {
        if (example == null) {
            return;
        }

        String parmPhrase1;
        String parmPhrase1_th;
        String parmPhrase2;
        String parmPhrase2_th;
        String parmPhrase3;
        String parmPhrase3_th;
        if (includeExamplePhrase) {
            parmPhrase1 = "%s #{example.oredCriteria[%d].allCriteria[%d].value}";
            parmPhrase1_th = "%s #{example.oredCriteria[%d].allCriteria[%d].value,typeHandler=%s}";
            parmPhrase2 = "%s #{example.oredCriteria[%d].allCriteria[%d].value} and #{example.oredCriteria[%d].criteria[%d].secondValue}";
            parmPhrase2_th = "%s #{example.oredCriteria[%d].allCriteria[%d].value,typeHandler=%s} and #{example.oredCriteria[%d].criteria[%d].secondValue,typeHandler=%s}";
            parmPhrase3 = "#{example.oredCriteria[%d].allCriteria[%d].value[%d]}";
            parmPhrase3_th = "#{example.oredCriteria[%d].allCriteria[%d].value[%d],typeHandler=%s}";
        } else {
            parmPhrase1 = "%s #{oredCriteria[%d].allCriteria[%d].value}";
            parmPhrase1_th = "%s #{oredCriteria[%d].allCriteria[%d].value,typeHandler=%s}";
            parmPhrase2 = "%s #{oredCriteria[%d].allCriteria[%d].value} and #{oredCriteria[%d].criteria[%d].secondValue}";
            parmPhrase2_th = "%s #{oredCriteria[%d].allCriteria[%d].value,typeHandler=%s} and #{oredCriteria[%d].criteria[%d].secondValue,typeHandler=%s}";
            parmPhrase3 = "#{oredCriteria[%d].allCriteria[%d].value[%d]}";
            parmPhrase3_th = "#{oredCriteria[%d].allCriteria[%d].value[%d],typeHandler=%s}";
        }

        StringBuilder sb = new StringBuilder();
        List<Criteria> oredCriteria = example.getOredCriteria();
        boolean firstCriteria = true;
        for (int i = 0; i < oredCriteria.size(); i++) {
            Criteria criteria = oredCriteria.get(i);
            if (criteria.isValid()) {
                if (firstCriteria) {
                    firstCriteria = false;
                } else {
                    sb.append(" or ");
                }

                sb.append('(');
                List<Criterion> criterions = criteria.getAllCriteria();
                boolean firstCriterion = true;
                for (int j = 0; j < criterions.size(); j++) {
                    Criterion criterion = criterions.get(j);
                    if (firstCriterion) {
                        firstCriterion = false;
                    } else {
                        sb.append(" and ");
                    }

                    if (criterion.isNoValue()) {
                        sb.append(criterion.getCondition());
                    } else if (criterion.isSingleValue()) {
                        if (criterion.getTypeHandler() == null) {
                            sb.append(String.format(parmPhrase1, criterion.getCondition(), i, j));
                        } else {
                            sb.append(String.format(parmPhrase1_th, criterion.getCondition(), i, j, criterion.getTypeHandler()));
                        }
                    } else if (criterion.isBetweenValue()) {
                        if (criterion.getTypeHandler() == null) {
                            sb.append(String.format(parmPhrase2, criterion.getCondition(), i, j, i, j));
                        } else {
                            sb.append(String.format(parmPhrase2_th, criterion.getCondition(), i, j, criterion.getTypeHandler(), i, j, criterion.getTypeHandler()));
                        }
                    } else if (criterion.isListValue()) {
                        sb.append(criterion.getCondition());
                        sb.append(" (");
                        List<?> listItems = (List<?>) criterion.getValue();
                        boolean comma = false;
                        for (int k = 0; k < listItems.size(); k++) {
                            if (comma) {
                                sb.append(", ");
                            } else {
                                comma = true;
                            }
                            if (criterion.getTypeHandler() == null) {
                                sb.append(String.format(parmPhrase3, i, j, k));
                            } else {
                                sb.append(String.format(parmPhrase3_th, i, j, k, criterion.getTypeHandler()));
                            }
                        }
                        sb.append(')');
                    }
                }
                sb.append(')');
            }
        }

        if (sb.length() > 0) {
            sql.WHERE(sb.toString());
        }
    }
}