package com.magicliang.transaction.sys.common.dal.mybatis.po;

import java.util.ArrayList;
import java.util.Date;
import java.util.List;

public class TransChannelRequestPoExample {
    /**
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database table tb_trans_channel_request
     *
     * @mbg.generated Wed Jan 26 17:49:11 CST 2022
     */
    protected String orderByClause;

    /**
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database table tb_trans_channel_request
     *
     * @mbg.generated Wed Jan 26 17:49:11 CST 2022
     */
    protected boolean distinct;

    /**
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database table tb_trans_channel_request
     *
     * @mbg.generated Wed Jan 26 17:49:11 CST 2022
     */
    protected List<Criteria> oredCriteria;

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table tb_trans_channel_request
     *
     * @mbg.generated Wed Jan 26 17:49:11 CST 2022
     */
    public TransChannelRequestPoExample() {
        oredCriteria = new ArrayList<>();
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table tb_trans_channel_request
     *
     * @mbg.generated Wed Jan 26 17:49:11 CST 2022
     */
    public String getOrderByClause() {
        return orderByClause;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table tb_trans_channel_request
     *
     * @mbg.generated Wed Jan 26 17:49:11 CST 2022
     */
    public void setOrderByClause(String orderByClause) {
        this.orderByClause = orderByClause;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table tb_trans_channel_request
     *
     * @mbg.generated Wed Jan 26 17:49:11 CST 2022
     */
    public boolean isDistinct() {
        return distinct;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table tb_trans_channel_request
     *
     * @mbg.generated Wed Jan 26 17:49:11 CST 2022
     */
    public void setDistinct(boolean distinct) {
        this.distinct = distinct;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table tb_trans_channel_request
     *
     * @mbg.generated Wed Jan 26 17:49:11 CST 2022
     */
    public List<Criteria> getOredCriteria() {
        return oredCriteria;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table tb_trans_channel_request
     *
     * @mbg.generated Wed Jan 26 17:49:11 CST 2022
     */
    public void or(Criteria criteria) {
        oredCriteria.add(criteria);
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table tb_trans_channel_request
     *
     * @mbg.generated Wed Jan 26 17:49:11 CST 2022
     */
    public Criteria or() {
        Criteria criteria = createCriteriaInternal();
        oredCriteria.add(criteria);
        return criteria;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table tb_trans_channel_request
     *
     * @mbg.generated Wed Jan 26 17:49:11 CST 2022
     */
    public Criteria createCriteria() {
        Criteria criteria = createCriteriaInternal();
        if (oredCriteria.size() == 0) {
            oredCriteria.add(criteria);
        }
        return criteria;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table tb_trans_channel_request
     *
     * @mbg.generated Wed Jan 26 17:49:11 CST 2022
     */
    protected Criteria createCriteriaInternal() {
        Criteria criteria = new Criteria();
        return criteria;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table tb_trans_channel_request
     *
     * @mbg.generated Wed Jan 26 17:49:11 CST 2022
     */
    public void clear() {
        oredCriteria.clear();
        orderByClause = null;
        distinct = false;
    }

    /**
     * This class was generated by MyBatis Generator.
     * This class corresponds to the database table tb_trans_channel_request
     *
     * @mbg.generated Wed Jan 26 17:49:11 CST 2022
     */
    protected abstract static class GeneratedCriteria {
        protected List<Criterion> criteria;

        protected GeneratedCriteria() {
            super();
            criteria = new ArrayList<>();
        }

        public boolean isValid() {
            return criteria.size() > 0;
        }

        public List<Criterion> getAllCriteria() {
            return criteria;
        }

        public List<Criterion> getCriteria() {
            return criteria;
        }

        protected void addCriterion(String condition) {
            if (condition == null) {
                throw new RuntimeException("Value for condition cannot be null");
            }
            criteria.add(new Criterion(condition));
        }

        protected void addCriterion(String condition, Object value, String property) {
            if (value == null) {
                throw new RuntimeException("Value for " + property + " cannot be null");
            }
            criteria.add(new Criterion(condition, value));
        }

        protected void addCriterion(String condition, Object value1, Object value2, String property) {
            if (value1 == null || value2 == null) {
                throw new RuntimeException("Between values for " + property + " cannot be null");
            }
            criteria.add(new Criterion(condition, value1, value2));
        }

        public Criteria andIdIsNull() {
            addCriterion("id is null");
            return (Criteria) this;
        }

        public Criteria andIdIsNotNull() {
            addCriterion("id is not null");
            return (Criteria) this;
        }

        public Criteria andIdEqualTo(Long value) {
            addCriterion("id =", value, "id");
            return (Criteria) this;
        }

        public Criteria andIdNotEqualTo(Long value) {
            addCriterion("id <>", value, "id");
            return (Criteria) this;
        }

        public Criteria andIdGreaterThan(Long value) {
            addCriterion("id >", value, "id");
            return (Criteria) this;
        }

        public Criteria andIdGreaterThanOrEqualTo(Long value) {
            addCriterion("id >=", value, "id");
            return (Criteria) this;
        }

        public Criteria andIdLessThan(Long value) {
            addCriterion("id <", value, "id");
            return (Criteria) this;
        }

        public Criteria andIdLessThanOrEqualTo(Long value) {
            addCriterion("id <=", value, "id");
            return (Criteria) this;
        }

        public Criteria andIdIn(List<Long> values) {
            addCriterion("id in", values, "id");
            return (Criteria) this;
        }

        public Criteria andIdNotIn(List<Long> values) {
            addCriterion("id not in", values, "id");
            return (Criteria) this;
        }

        public Criteria andIdBetween(Long value1, Long value2) {
            addCriterion("id between", value1, value2, "id");
            return (Criteria) this;
        }

        public Criteria andIdNotBetween(Long value1, Long value2) {
            addCriterion("id not between", value1, value2, "id");
            return (Criteria) this;
        }

        public Criteria andGmtCreatedIsNull() {
            addCriterion("gmt_created is null");
            return (Criteria) this;
        }

        public Criteria andGmtCreatedIsNotNull() {
            addCriterion("gmt_created is not null");
            return (Criteria) this;
        }

        public Criteria andGmtCreatedEqualTo(Date value) {
            addCriterion("gmt_created =", value, "gmtCreated");
            return (Criteria) this;
        }

        public Criteria andGmtCreatedNotEqualTo(Date value) {
            addCriterion("gmt_created <>", value, "gmtCreated");
            return (Criteria) this;
        }

        public Criteria andGmtCreatedGreaterThan(Date value) {
            addCriterion("gmt_created >", value, "gmtCreated");
            return (Criteria) this;
        }

        public Criteria andGmtCreatedGreaterThanOrEqualTo(Date value) {
            addCriterion("gmt_created >=", value, "gmtCreated");
            return (Criteria) this;
        }

        public Criteria andGmtCreatedLessThan(Date value) {
            addCriterion("gmt_created <", value, "gmtCreated");
            return (Criteria) this;
        }

        public Criteria andGmtCreatedLessThanOrEqualTo(Date value) {
            addCriterion("gmt_created <=", value, "gmtCreated");
            return (Criteria) this;
        }

        public Criteria andGmtCreatedIn(List<Date> values) {
            addCriterion("gmt_created in", values, "gmtCreated");
            return (Criteria) this;
        }

        public Criteria andGmtCreatedNotIn(List<Date> values) {
            addCriterion("gmt_created not in", values, "gmtCreated");
            return (Criteria) this;
        }

        public Criteria andGmtCreatedBetween(Date value1, Date value2) {
            addCriterion("gmt_created between", value1, value2, "gmtCreated");
            return (Criteria) this;
        }

        public Criteria andGmtCreatedNotBetween(Date value1, Date value2) {
            addCriterion("gmt_created not between", value1, value2, "gmtCreated");
            return (Criteria) this;
        }

        public Criteria andGmtModifiedIsNull() {
            addCriterion("gmt_modified is null");
            return (Criteria) this;
        }

        public Criteria andGmtModifiedIsNotNull() {
            addCriterion("gmt_modified is not null");
            return (Criteria) this;
        }

        public Criteria andGmtModifiedEqualTo(Date value) {
            addCriterion("gmt_modified =", value, "gmtModified");
            return (Criteria) this;
        }

        public Criteria andGmtModifiedNotEqualTo(Date value) {
            addCriterion("gmt_modified <>", value, "gmtModified");
            return (Criteria) this;
        }

        public Criteria andGmtModifiedGreaterThan(Date value) {
            addCriterion("gmt_modified >", value, "gmtModified");
            return (Criteria) this;
        }

        public Criteria andGmtModifiedGreaterThanOrEqualTo(Date value) {
            addCriterion("gmt_modified >=", value, "gmtModified");
            return (Criteria) this;
        }

        public Criteria andGmtModifiedLessThan(Date value) {
            addCriterion("gmt_modified <", value, "gmtModified");
            return (Criteria) this;
        }

        public Criteria andGmtModifiedLessThanOrEqualTo(Date value) {
            addCriterion("gmt_modified <=", value, "gmtModified");
            return (Criteria) this;
        }

        public Criteria andGmtModifiedIn(List<Date> values) {
            addCriterion("gmt_modified in", values, "gmtModified");
            return (Criteria) this;
        }

        public Criteria andGmtModifiedNotIn(List<Date> values) {
            addCriterion("gmt_modified not in", values, "gmtModified");
            return (Criteria) this;
        }

        public Criteria andGmtModifiedBetween(Date value1, Date value2) {
            addCriterion("gmt_modified between", value1, value2, "gmtModified");
            return (Criteria) this;
        }

        public Criteria andGmtModifiedNotBetween(Date value1, Date value2) {
            addCriterion("gmt_modified not between", value1, value2, "gmtModified");
            return (Criteria) this;
        }

        public Criteria andPayOrderNoIsNull() {
            addCriterion("pay_order_no is null");
            return (Criteria) this;
        }

        public Criteria andPayOrderNoIsNotNull() {
            addCriterion("pay_order_no is not null");
            return (Criteria) this;
        }

        public Criteria andPayOrderNoEqualTo(Long value) {
            addCriterion("pay_order_no =", value, "payOrderNo");
            return (Criteria) this;
        }

        public Criteria andPayOrderNoNotEqualTo(Long value) {
            addCriterion("pay_order_no <>", value, "payOrderNo");
            return (Criteria) this;
        }

        public Criteria andPayOrderNoGreaterThan(Long value) {
            addCriterion("pay_order_no >", value, "payOrderNo");
            return (Criteria) this;
        }

        public Criteria andPayOrderNoGreaterThanOrEqualTo(Long value) {
            addCriterion("pay_order_no >=", value, "payOrderNo");
            return (Criteria) this;
        }

        public Criteria andPayOrderNoLessThan(Long value) {
            addCriterion("pay_order_no <", value, "payOrderNo");
            return (Criteria) this;
        }

        public Criteria andPayOrderNoLessThanOrEqualTo(Long value) {
            addCriterion("pay_order_no <=", value, "payOrderNo");
            return (Criteria) this;
        }

        public Criteria andPayOrderNoIn(List<Long> values) {
            addCriterion("pay_order_no in", values, "payOrderNo");
            return (Criteria) this;
        }

        public Criteria andPayOrderNoNotIn(List<Long> values) {
            addCriterion("pay_order_no not in", values, "payOrderNo");
            return (Criteria) this;
        }

        public Criteria andPayOrderNoBetween(Long value1, Long value2) {
            addCriterion("pay_order_no between", value1, value2, "payOrderNo");
            return (Criteria) this;
        }

        public Criteria andPayOrderNoNotBetween(Long value1, Long value2) {
            addCriterion("pay_order_no not between", value1, value2, "payOrderNo");
            return (Criteria) this;
        }

        public Criteria andRequestTypeIsNull() {
            addCriterion("request_type is null");
            return (Criteria) this;
        }

        public Criteria andRequestTypeIsNotNull() {
            addCriterion("request_type is not null");
            return (Criteria) this;
        }

        public Criteria andRequestTypeEqualTo(Integer value) {
            addCriterion("request_type =", value, "requestType");
            return (Criteria) this;
        }

        public Criteria andRequestTypeNotEqualTo(Integer value) {
            addCriterion("request_type <>", value, "requestType");
            return (Criteria) this;
        }

        public Criteria andRequestTypeGreaterThan(Integer value) {
            addCriterion("request_type >", value, "requestType");
            return (Criteria) this;
        }

        public Criteria andRequestTypeGreaterThanOrEqualTo(Integer value) {
            addCriterion("request_type >=", value, "requestType");
            return (Criteria) this;
        }

        public Criteria andRequestTypeLessThan(Integer value) {
            addCriterion("request_type <", value, "requestType");
            return (Criteria) this;
        }

        public Criteria andRequestTypeLessThanOrEqualTo(Integer value) {
            addCriterion("request_type <=", value, "requestType");
            return (Criteria) this;
        }

        public Criteria andRequestTypeIn(List<Integer> values) {
            addCriterion("request_type in", values, "requestType");
            return (Criteria) this;
        }

        public Criteria andRequestTypeNotIn(List<Integer> values) {
            addCriterion("request_type not in", values, "requestType");
            return (Criteria) this;
        }

        public Criteria andRequestTypeBetween(Integer value1, Integer value2) {
            addCriterion("request_type between", value1, value2, "requestType");
            return (Criteria) this;
        }

        public Criteria andRequestTypeNotBetween(Integer value1, Integer value2) {
            addCriterion("request_type not between", value1, value2, "requestType");
            return (Criteria) this;
        }

        public Criteria andBizIdentifyNoIsNull() {
            addCriterion("biz_identify_no is null");
            return (Criteria) this;
        }

        public Criteria andBizIdentifyNoIsNotNull() {
            addCriterion("biz_identify_no is not null");
            return (Criteria) this;
        }

        public Criteria andBizIdentifyNoEqualTo(String value) {
            addCriterion("biz_identify_no =", value, "bizIdentifyNo");
            return (Criteria) this;
        }

        public Criteria andBizIdentifyNoNotEqualTo(String value) {
            addCriterion("biz_identify_no <>", value, "bizIdentifyNo");
            return (Criteria) this;
        }

        public Criteria andBizIdentifyNoGreaterThan(String value) {
            addCriterion("biz_identify_no >", value, "bizIdentifyNo");
            return (Criteria) this;
        }

        public Criteria andBizIdentifyNoGreaterThanOrEqualTo(String value) {
            addCriterion("biz_identify_no >=", value, "bizIdentifyNo");
            return (Criteria) this;
        }

        public Criteria andBizIdentifyNoLessThan(String value) {
            addCriterion("biz_identify_no <", value, "bizIdentifyNo");
            return (Criteria) this;
        }

        public Criteria andBizIdentifyNoLessThanOrEqualTo(String value) {
            addCriterion("biz_identify_no <=", value, "bizIdentifyNo");
            return (Criteria) this;
        }

        public Criteria andBizIdentifyNoLike(String value) {
            addCriterion("biz_identify_no like", value, "bizIdentifyNo");
            return (Criteria) this;
        }

        public Criteria andBizIdentifyNoNotLike(String value) {
            addCriterion("biz_identify_no not like", value, "bizIdentifyNo");
            return (Criteria) this;
        }

        public Criteria andBizIdentifyNoIn(List<String> values) {
            addCriterion("biz_identify_no in", values, "bizIdentifyNo");
            return (Criteria) this;
        }

        public Criteria andBizIdentifyNoNotIn(List<String> values) {
            addCriterion("biz_identify_no not in", values, "bizIdentifyNo");
            return (Criteria) this;
        }

        public Criteria andBizIdentifyNoBetween(String value1, String value2) {
            addCriterion("biz_identify_no between", value1, value2, "bizIdentifyNo");
            return (Criteria) this;
        }

        public Criteria andBizIdentifyNoNotBetween(String value1, String value2) {
            addCriterion("biz_identify_no not between", value1, value2, "bizIdentifyNo");
            return (Criteria) this;
        }

        public Criteria andBizUniqueNoIsNull() {
            addCriterion("biz_unique_no is null");
            return (Criteria) this;
        }

        public Criteria andBizUniqueNoIsNotNull() {
            addCriterion("biz_unique_no is not null");
            return (Criteria) this;
        }

        public Criteria andBizUniqueNoEqualTo(String value) {
            addCriterion("biz_unique_no =", value, "bizUniqueNo");
            return (Criteria) this;
        }

        public Criteria andBizUniqueNoNotEqualTo(String value) {
            addCriterion("biz_unique_no <>", value, "bizUniqueNo");
            return (Criteria) this;
        }

        public Criteria andBizUniqueNoGreaterThan(String value) {
            addCriterion("biz_unique_no >", value, "bizUniqueNo");
            return (Criteria) this;
        }

        public Criteria andBizUniqueNoGreaterThanOrEqualTo(String value) {
            addCriterion("biz_unique_no >=", value, "bizUniqueNo");
            return (Criteria) this;
        }

        public Criteria andBizUniqueNoLessThan(String value) {
            addCriterion("biz_unique_no <", value, "bizUniqueNo");
            return (Criteria) this;
        }

        public Criteria andBizUniqueNoLessThanOrEqualTo(String value) {
            addCriterion("biz_unique_no <=", value, "bizUniqueNo");
            return (Criteria) this;
        }

        public Criteria andBizUniqueNoLike(String value) {
            addCriterion("biz_unique_no like", value, "bizUniqueNo");
            return (Criteria) this;
        }

        public Criteria andBizUniqueNoNotLike(String value) {
            addCriterion("biz_unique_no not like", value, "bizUniqueNo");
            return (Criteria) this;
        }

        public Criteria andBizUniqueNoIn(List<String> values) {
            addCriterion("biz_unique_no in", values, "bizUniqueNo");
            return (Criteria) this;
        }

        public Criteria andBizUniqueNoNotIn(List<String> values) {
            addCriterion("biz_unique_no not in", values, "bizUniqueNo");
            return (Criteria) this;
        }

        public Criteria andBizUniqueNoBetween(String value1, String value2) {
            addCriterion("biz_unique_no between", value1, value2, "bizUniqueNo");
            return (Criteria) this;
        }

        public Criteria andBizUniqueNoNotBetween(String value1, String value2) {
            addCriterion("biz_unique_no not between", value1, value2, "bizUniqueNo");
            return (Criteria) this;
        }

        public Criteria andGmtNextExecutionIsNull() {
            addCriterion("gmt_next_execution is null");
            return (Criteria) this;
        }

        public Criteria andGmtNextExecutionIsNotNull() {
            addCriterion("gmt_next_execution is not null");
            return (Criteria) this;
        }

        public Criteria andGmtNextExecutionEqualTo(Date value) {
            addCriterion("gmt_next_execution =", value, "gmtNextExecution");
            return (Criteria) this;
        }

        public Criteria andGmtNextExecutionNotEqualTo(Date value) {
            addCriterion("gmt_next_execution <>", value, "gmtNextExecution");
            return (Criteria) this;
        }

        public Criteria andGmtNextExecutionGreaterThan(Date value) {
            addCriterion("gmt_next_execution >", value, "gmtNextExecution");
            return (Criteria) this;
        }

        public Criteria andGmtNextExecutionGreaterThanOrEqualTo(Date value) {
            addCriterion("gmt_next_execution >=", value, "gmtNextExecution");
            return (Criteria) this;
        }

        public Criteria andGmtNextExecutionLessThan(Date value) {
            addCriterion("gmt_next_execution <", value, "gmtNextExecution");
            return (Criteria) this;
        }

        public Criteria andGmtNextExecutionLessThanOrEqualTo(Date value) {
            addCriterion("gmt_next_execution <=", value, "gmtNextExecution");
            return (Criteria) this;
        }

        public Criteria andGmtNextExecutionIn(List<Date> values) {
            addCriterion("gmt_next_execution in", values, "gmtNextExecution");
            return (Criteria) this;
        }

        public Criteria andGmtNextExecutionNotIn(List<Date> values) {
            addCriterion("gmt_next_execution not in", values, "gmtNextExecution");
            return (Criteria) this;
        }

        public Criteria andGmtNextExecutionBetween(Date value1, Date value2) {
            addCriterion("gmt_next_execution between", value1, value2, "gmtNextExecution");
            return (Criteria) this;
        }

        public Criteria andGmtNextExecutionNotBetween(Date value1, Date value2) {
            addCriterion("gmt_next_execution not between", value1, value2, "gmtNextExecution");
            return (Criteria) this;
        }

        public Criteria andRetryCountIsNull() {
            addCriterion("retry_count is null");
            return (Criteria) this;
        }

        public Criteria andRetryCountIsNotNull() {
            addCriterion("retry_count is not null");
            return (Criteria) this;
        }

        public Criteria andRetryCountEqualTo(Long value) {
            addCriterion("retry_count =", value, "retryCount");
            return (Criteria) this;
        }

        public Criteria andRetryCountNotEqualTo(Long value) {
            addCriterion("retry_count <>", value, "retryCount");
            return (Criteria) this;
        }

        public Criteria andRetryCountGreaterThan(Long value) {
            addCriterion("retry_count >", value, "retryCount");
            return (Criteria) this;
        }

        public Criteria andRetryCountGreaterThanOrEqualTo(Long value) {
            addCriterion("retry_count >=", value, "retryCount");
            return (Criteria) this;
        }

        public Criteria andRetryCountLessThan(Long value) {
            addCriterion("retry_count <", value, "retryCount");
            return (Criteria) this;
        }

        public Criteria andRetryCountLessThanOrEqualTo(Long value) {
            addCriterion("retry_count <=", value, "retryCount");
            return (Criteria) this;
        }

        public Criteria andRetryCountIn(List<Long> values) {
            addCriterion("retry_count in", values, "retryCount");
            return (Criteria) this;
        }

        public Criteria andRetryCountNotIn(List<Long> values) {
            addCriterion("retry_count not in", values, "retryCount");
            return (Criteria) this;
        }

        public Criteria andRetryCountBetween(Long value1, Long value2) {
            addCriterion("retry_count between", value1, value2, "retryCount");
            return (Criteria) this;
        }

        public Criteria andRetryCountNotBetween(Long value1, Long value2) {
            addCriterion("retry_count not between", value1, value2, "retryCount");
            return (Criteria) this;
        }

        public Criteria andRequestAddrIsNull() {
            addCriterion("request_addr is null");
            return (Criteria) this;
        }

        public Criteria andRequestAddrIsNotNull() {
            addCriterion("request_addr is not null");
            return (Criteria) this;
        }

        public Criteria andRequestAddrEqualTo(String value) {
            addCriterion("request_addr =", value, "requestAddr");
            return (Criteria) this;
        }

        public Criteria andRequestAddrNotEqualTo(String value) {
            addCriterion("request_addr <>", value, "requestAddr");
            return (Criteria) this;
        }

        public Criteria andRequestAddrGreaterThan(String value) {
            addCriterion("request_addr >", value, "requestAddr");
            return (Criteria) this;
        }

        public Criteria andRequestAddrGreaterThanOrEqualTo(String value) {
            addCriterion("request_addr >=", value, "requestAddr");
            return (Criteria) this;
        }

        public Criteria andRequestAddrLessThan(String value) {
            addCriterion("request_addr <", value, "requestAddr");
            return (Criteria) this;
        }

        public Criteria andRequestAddrLessThanOrEqualTo(String value) {
            addCriterion("request_addr <=", value, "requestAddr");
            return (Criteria) this;
        }

        public Criteria andRequestAddrLike(String value) {
            addCriterion("request_addr like", value, "requestAddr");
            return (Criteria) this;
        }

        public Criteria andRequestAddrNotLike(String value) {
            addCriterion("request_addr not like", value, "requestAddr");
            return (Criteria) this;
        }

        public Criteria andRequestAddrIn(List<String> values) {
            addCriterion("request_addr in", values, "requestAddr");
            return (Criteria) this;
        }

        public Criteria andRequestAddrNotIn(List<String> values) {
            addCriterion("request_addr not in", values, "requestAddr");
            return (Criteria) this;
        }

        public Criteria andRequestAddrBetween(String value1, String value2) {
            addCriterion("request_addr between", value1, value2, "requestAddr");
            return (Criteria) this;
        }

        public Criteria andRequestAddrNotBetween(String value1, String value2) {
            addCriterion("request_addr not between", value1, value2, "requestAddr");
            return (Criteria) this;
        }

        public Criteria andStatusIsNull() {
            addCriterion("status is null");
            return (Criteria) this;
        }

        public Criteria andStatusIsNotNull() {
            addCriterion("status is not null");
            return (Criteria) this;
        }

        public Criteria andStatusEqualTo(Integer value) {
            addCriterion("status =", value, "status");
            return (Criteria) this;
        }

        public Criteria andStatusNotEqualTo(Integer value) {
            addCriterion("status <>", value, "status");
            return (Criteria) this;
        }

        public Criteria andStatusGreaterThan(Integer value) {
            addCriterion("status >", value, "status");
            return (Criteria) this;
        }

        public Criteria andStatusGreaterThanOrEqualTo(Integer value) {
            addCriterion("status >=", value, "status");
            return (Criteria) this;
        }

        public Criteria andStatusLessThan(Integer value) {
            addCriterion("status <", value, "status");
            return (Criteria) this;
        }

        public Criteria andStatusLessThanOrEqualTo(Integer value) {
            addCriterion("status <=", value, "status");
            return (Criteria) this;
        }

        public Criteria andStatusIn(List<Integer> values) {
            addCriterion("status in", values, "status");
            return (Criteria) this;
        }

        public Criteria andStatusNotIn(List<Integer> values) {
            addCriterion("status not in", values, "status");
            return (Criteria) this;
        }

        public Criteria andStatusBetween(Integer value1, Integer value2) {
            addCriterion("status between", value1, value2, "status");
            return (Criteria) this;
        }

        public Criteria andStatusNotBetween(Integer value1, Integer value2) {
            addCriterion("status not between", value1, value2, "status");
            return (Criteria) this;
        }

        public Criteria andCloseReasonIsNull() {
            addCriterion("close_reason is null");
            return (Criteria) this;
        }

        public Criteria andCloseReasonIsNotNull() {
            addCriterion("close_reason is not null");
            return (Criteria) this;
        }

        public Criteria andCloseReasonEqualTo(Integer value) {
            addCriterion("close_reason =", value, "closeReason");
            return (Criteria) this;
        }

        public Criteria andCloseReasonNotEqualTo(Integer value) {
            addCriterion("close_reason <>", value, "closeReason");
            return (Criteria) this;
        }

        public Criteria andCloseReasonGreaterThan(Integer value) {
            addCriterion("close_reason >", value, "closeReason");
            return (Criteria) this;
        }

        public Criteria andCloseReasonGreaterThanOrEqualTo(Integer value) {
            addCriterion("close_reason >=", value, "closeReason");
            return (Criteria) this;
        }

        public Criteria andCloseReasonLessThan(Integer value) {
            addCriterion("close_reason <", value, "closeReason");
            return (Criteria) this;
        }

        public Criteria andCloseReasonLessThanOrEqualTo(Integer value) {
            addCriterion("close_reason <=", value, "closeReason");
            return (Criteria) this;
        }

        public Criteria andCloseReasonIn(List<Integer> values) {
            addCriterion("close_reason in", values, "closeReason");
            return (Criteria) this;
        }

        public Criteria andCloseReasonNotIn(List<Integer> values) {
            addCriterion("close_reason not in", values, "closeReason");
            return (Criteria) this;
        }

        public Criteria andCloseReasonBetween(Integer value1, Integer value2) {
            addCriterion("close_reason between", value1, value2, "closeReason");
            return (Criteria) this;
        }

        public Criteria andCloseReasonNotBetween(Integer value1, Integer value2) {
            addCriterion("close_reason not between", value1, value2, "closeReason");
            return (Criteria) this;
        }

        public Criteria andGmtLastExecutionIsNull() {
            addCriterion("gmt_last_execution is null");
            return (Criteria) this;
        }

        public Criteria andGmtLastExecutionIsNotNull() {
            addCriterion("gmt_last_execution is not null");
            return (Criteria) this;
        }

        public Criteria andGmtLastExecutionEqualTo(Date value) {
            addCriterion("gmt_last_execution =", value, "gmtLastExecution");
            return (Criteria) this;
        }

        public Criteria andGmtLastExecutionNotEqualTo(Date value) {
            addCriterion("gmt_last_execution <>", value, "gmtLastExecution");
            return (Criteria) this;
        }

        public Criteria andGmtLastExecutionGreaterThan(Date value) {
            addCriterion("gmt_last_execution >", value, "gmtLastExecution");
            return (Criteria) this;
        }

        public Criteria andGmtLastExecutionGreaterThanOrEqualTo(Date value) {
            addCriterion("gmt_last_execution >=", value, "gmtLastExecution");
            return (Criteria) this;
        }

        public Criteria andGmtLastExecutionLessThan(Date value) {
            addCriterion("gmt_last_execution <", value, "gmtLastExecution");
            return (Criteria) this;
        }

        public Criteria andGmtLastExecutionLessThanOrEqualTo(Date value) {
            addCriterion("gmt_last_execution <=", value, "gmtLastExecution");
            return (Criteria) this;
        }

        public Criteria andGmtLastExecutionIn(List<Date> values) {
            addCriterion("gmt_last_execution in", values, "gmtLastExecution");
            return (Criteria) this;
        }

        public Criteria andGmtLastExecutionNotIn(List<Date> values) {
            addCriterion("gmt_last_execution not in", values, "gmtLastExecution");
            return (Criteria) this;
        }

        public Criteria andGmtLastExecutionBetween(Date value1, Date value2) {
            addCriterion("gmt_last_execution between", value1, value2, "gmtLastExecution");
            return (Criteria) this;
        }

        public Criteria andGmtLastExecutionNotBetween(Date value1, Date value2) {
            addCriterion("gmt_last_execution not between", value1, value2, "gmtLastExecution");
            return (Criteria) this;
        }

        public Criteria andEnvIsNull() {
            addCriterion("env is null");
            return (Criteria) this;
        }

        public Criteria andEnvIsNotNull() {
            addCriterion("env is not null");
            return (Criteria) this;
        }

        public Criteria andEnvEqualTo(Integer value) {
            addCriterion("env =", value, "env");
            return (Criteria) this;
        }

        public Criteria andEnvNotEqualTo(Integer value) {
            addCriterion("env <>", value, "env");
            return (Criteria) this;
        }

        public Criteria andEnvGreaterThan(Integer value) {
            addCriterion("env >", value, "env");
            return (Criteria) this;
        }

        public Criteria andEnvGreaterThanOrEqualTo(Integer value) {
            addCriterion("env >=", value, "env");
            return (Criteria) this;
        }

        public Criteria andEnvLessThan(Integer value) {
            addCriterion("env <", value, "env");
            return (Criteria) this;
        }

        public Criteria andEnvLessThanOrEqualTo(Integer value) {
            addCriterion("env <=", value, "env");
            return (Criteria) this;
        }

        public Criteria andEnvIn(List<Integer> values) {
            addCriterion("env in", values, "env");
            return (Criteria) this;
        }

        public Criteria andEnvNotIn(List<Integer> values) {
            addCriterion("env not in", values, "env");
            return (Criteria) this;
        }

        public Criteria andEnvBetween(Integer value1, Integer value2) {
            addCriterion("env between", value1, value2, "env");
            return (Criteria) this;
        }

        public Criteria andEnvNotBetween(Integer value1, Integer value2) {
            addCriterion("env not between", value1, value2, "env");
            return (Criteria) this;
        }
    }

    /**
     * This class was generated by MyBatis Generator.
     * This class corresponds to the database table tb_trans_channel_request
     *
     * @mbg.generated do_not_delete_during_merge Wed Jan 26 17:49:11 CST 2022
     */
    public static class Criteria extends GeneratedCriteria {
        protected Criteria() {
            super();
        }
    }

    /**
     * This class was generated by MyBatis Generator.
     * This class corresponds to the database table tb_trans_channel_request
     *
     * @mbg.generated Wed Jan 26 17:49:11 CST 2022
     */
    public static class Criterion {
        private String condition;

        private Object value;

        private Object secondValue;

        private boolean noValue;

        private boolean singleValue;

        private boolean betweenValue;

        private boolean listValue;

        private String typeHandler;

        protected Criterion(String condition) {
            super();
            this.condition = condition;
            this.typeHandler = null;
            this.noValue = true;
        }

        protected Criterion(String condition, Object value, String typeHandler) {
            super();
            this.condition = condition;
            this.value = value;
            this.typeHandler = typeHandler;
            if (value instanceof List<?>) {
                this.listValue = true;
            } else {
                this.singleValue = true;
            }
        }

        protected Criterion(String condition, Object value) {
            this(condition, value, null);
        }

        protected Criterion(String condition, Object value, Object secondValue, String typeHandler) {
            super();
            this.condition = condition;
            this.value = value;
            this.secondValue = secondValue;
            this.typeHandler = typeHandler;
            this.betweenValue = true;
        }

        protected Criterion(String condition, Object value, Object secondValue) {
            this(condition, value, secondValue, null);
        }

        public String getCondition() {
            return condition;
        }

        public Object getValue() {
            return value;
        }

        public Object getSecondValue() {
            return secondValue;
        }

        public boolean isNoValue() {
            return noValue;
        }

        public boolean isSingleValue() {
            return singleValue;
        }

        public boolean isBetweenValue() {
            return betweenValue;
        }

        public boolean isListValue() {
            return listValue;
        }

        public String getTypeHandler() {
            return typeHandler;
        }
    }
}