package com.magicliang.transaction.sys.common.dal.mybatis.po;

import java.util.ArrayList;
import java.util.Date;
import java.util.List;

public class TransPayOrderPoExample {

    /**
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database table tb_trans_pay_order
     *
     * @mbg.generated Wed Jan 26 17:49:11 CST 2022
     */
    protected String orderByClause;

    /**
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database table tb_trans_pay_order
     *
     * @mbg.generated Wed Jan 26 17:49:11 CST 2022
     */
    protected boolean distinct;

    /**
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database table tb_trans_pay_order
     *
     * @mbg.generated Wed Jan 26 17:49:11 CST 2022
     */
    protected List<Criteria> oredCriteria;

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table tb_trans_pay_order
     *
     * @mbg.generated Wed Jan 26 17:49:11 CST 2022
     */
    public TransPayOrderPoExample() {
        oredCriteria = new ArrayList<>();
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table tb_trans_pay_order
     *
     * @mbg.generated Wed Jan 26 17:49:11 CST 2022
     */
    public String getOrderByClause() {
        return orderByClause;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table tb_trans_pay_order
     *
     * @mbg.generated Wed Jan 26 17:49:11 CST 2022
     */
    public void setOrderByClause(String orderByClause) {
        this.orderByClause = orderByClause;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table tb_trans_pay_order
     *
     * @mbg.generated Wed Jan 26 17:49:11 CST 2022
     */
    public boolean isDistinct() {
        return distinct;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table tb_trans_pay_order
     *
     * @mbg.generated Wed Jan 26 17:49:11 CST 2022
     */
    public void setDistinct(boolean distinct) {
        this.distinct = distinct;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table tb_trans_pay_order
     *
     * @mbg.generated Wed Jan 26 17:49:11 CST 2022
     */
    public List<Criteria> getOredCriteria() {
        return oredCriteria;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table tb_trans_pay_order
     *
     * @mbg.generated Wed Jan 26 17:49:11 CST 2022
     */
    public void or(Criteria criteria) {
        oredCriteria.add(criteria);
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table tb_trans_pay_order
     *
     * @mbg.generated Wed Jan 26 17:49:11 CST 2022
     */
    public Criteria or() {
        Criteria criteria = createCriteriaInternal();
        oredCriteria.add(criteria);
        return criteria;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table tb_trans_pay_order
     *
     * @mbg.generated Wed Jan 26 17:49:11 CST 2022
     */
    public Criteria createCriteria() {
        Criteria criteria = createCriteriaInternal();
        if (oredCriteria.size() == 0) {
            oredCriteria.add(criteria);
        }
        return criteria;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table tb_trans_pay_order
     *
     * @mbg.generated Wed Jan 26 17:49:11 CST 2022
     */
    protected Criteria createCriteriaInternal() {
        Criteria criteria = new Criteria();
        return criteria;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table tb_trans_pay_order
     *
     * @mbg.generated Wed Jan 26 17:49:11 CST 2022
     */
    public void clear() {
        oredCriteria.clear();
        orderByClause = null;
        distinct = false;
    }

    /**
     * This class was generated by MyBatis Generator.
     * This class corresponds to the database table tb_trans_pay_order
     *
     * @mbg.generated Wed Jan 26 17:49:11 CST 2022
     */
    protected abstract static class GeneratedCriteria {

        protected List<Criterion> criteria;

        protected GeneratedCriteria() {
            super();
            criteria = new ArrayList<>();
        }

        public boolean isValid() {
            return criteria.size() > 0;
        }

        public List<Criterion> getAllCriteria() {
            return criteria;
        }

        public List<Criterion> getCriteria() {
            return criteria;
        }

        protected void addCriterion(String condition) {
            if (condition == null) {
                throw new RuntimeException("Value for condition cannot be null");
            }
            criteria.add(new Criterion(condition));
        }

        protected void addCriterion(String condition, Object value, String property) {
            if (value == null) {
                throw new RuntimeException("Value for " + property + " cannot be null");
            }
            criteria.add(new Criterion(condition, value));
        }

        protected void addCriterion(String condition, Object value1, Object value2, String property) {
            if (value1 == null || value2 == null) {
                throw new RuntimeException("Between values for " + property + " cannot be null");
            }
            criteria.add(new Criterion(condition, value1, value2));
        }

        public Criteria andIdIsNull() {
            addCriterion("id is null");
            return (Criteria) this;
        }

        public Criteria andIdIsNotNull() {
            addCriterion("id is not null");
            return (Criteria) this;
        }

        public Criteria andIdEqualTo(Long value) {
            addCriterion("id =", value, "id");
            return (Criteria) this;
        }

        public Criteria andIdNotEqualTo(Long value) {
            addCriterion("id <>", value, "id");
            return (Criteria) this;
        }

        public Criteria andIdGreaterThan(Long value) {
            addCriterion("id >", value, "id");
            return (Criteria) this;
        }

        public Criteria andIdGreaterThanOrEqualTo(Long value) {
            addCriterion("id >=", value, "id");
            return (Criteria) this;
        }

        public Criteria andIdLessThan(Long value) {
            addCriterion("id <", value, "id");
            return (Criteria) this;
        }

        public Criteria andIdLessThanOrEqualTo(Long value) {
            addCriterion("id <=", value, "id");
            return (Criteria) this;
        }

        public Criteria andIdIn(List<Long> values) {
            addCriterion("id in", values, "id");
            return (Criteria) this;
        }

        public Criteria andIdNotIn(List<Long> values) {
            addCriterion("id not in", values, "id");
            return (Criteria) this;
        }

        public Criteria andIdBetween(Long value1, Long value2) {
            addCriterion("id between", value1, value2, "id");
            return (Criteria) this;
        }

        public Criteria andIdNotBetween(Long value1, Long value2) {
            addCriterion("id not between", value1, value2, "id");
            return (Criteria) this;
        }

        public Criteria andGmtCreatedIsNull() {
            addCriterion("gmt_created is null");
            return (Criteria) this;
        }

        public Criteria andGmtCreatedIsNotNull() {
            addCriterion("gmt_created is not null");
            return (Criteria) this;
        }

        public Criteria andGmtCreatedEqualTo(Date value) {
            addCriterion("gmt_created =", value, "gmtCreated");
            return (Criteria) this;
        }

        public Criteria andGmtCreatedNotEqualTo(Date value) {
            addCriterion("gmt_created <>", value, "gmtCreated");
            return (Criteria) this;
        }

        public Criteria andGmtCreatedGreaterThan(Date value) {
            addCriterion("gmt_created >", value, "gmtCreated");
            return (Criteria) this;
        }

        public Criteria andGmtCreatedGreaterThanOrEqualTo(Date value) {
            addCriterion("gmt_created >=", value, "gmtCreated");
            return (Criteria) this;
        }

        public Criteria andGmtCreatedLessThan(Date value) {
            addCriterion("gmt_created <", value, "gmtCreated");
            return (Criteria) this;
        }

        public Criteria andGmtCreatedLessThanOrEqualTo(Date value) {
            addCriterion("gmt_created <=", value, "gmtCreated");
            return (Criteria) this;
        }

        public Criteria andGmtCreatedIn(List<Date> values) {
            addCriterion("gmt_created in", values, "gmtCreated");
            return (Criteria) this;
        }

        public Criteria andGmtCreatedNotIn(List<Date> values) {
            addCriterion("gmt_created not in", values, "gmtCreated");
            return (Criteria) this;
        }

        public Criteria andGmtCreatedBetween(Date value1, Date value2) {
            addCriterion("gmt_created between", value1, value2, "gmtCreated");
            return (Criteria) this;
        }

        public Criteria andGmtCreatedNotBetween(Date value1, Date value2) {
            addCriterion("gmt_created not between", value1, value2, "gmtCreated");
            return (Criteria) this;
        }

        public Criteria andGmtModifiedIsNull() {
            addCriterion("gmt_modified is null");
            return (Criteria) this;
        }

        public Criteria andGmtModifiedIsNotNull() {
            addCriterion("gmt_modified is not null");
            return (Criteria) this;
        }

        public Criteria andGmtModifiedEqualTo(Date value) {
            addCriterion("gmt_modified =", value, "gmtModified");
            return (Criteria) this;
        }

        public Criteria andGmtModifiedNotEqualTo(Date value) {
            addCriterion("gmt_modified <>", value, "gmtModified");
            return (Criteria) this;
        }

        public Criteria andGmtModifiedGreaterThan(Date value) {
            addCriterion("gmt_modified >", value, "gmtModified");
            return (Criteria) this;
        }

        public Criteria andGmtModifiedGreaterThanOrEqualTo(Date value) {
            addCriterion("gmt_modified >=", value, "gmtModified");
            return (Criteria) this;
        }

        public Criteria andGmtModifiedLessThan(Date value) {
            addCriterion("gmt_modified <", value, "gmtModified");
            return (Criteria) this;
        }

        public Criteria andGmtModifiedLessThanOrEqualTo(Date value) {
            addCriterion("gmt_modified <=", value, "gmtModified");
            return (Criteria) this;
        }

        public Criteria andGmtModifiedIn(List<Date> values) {
            addCriterion("gmt_modified in", values, "gmtModified");
            return (Criteria) this;
        }

        public Criteria andGmtModifiedNotIn(List<Date> values) {
            addCriterion("gmt_modified not in", values, "gmtModified");
            return (Criteria) this;
        }

        public Criteria andGmtModifiedBetween(Date value1, Date value2) {
            addCriterion("gmt_modified between", value1, value2, "gmtModified");
            return (Criteria) this;
        }

        public Criteria andGmtModifiedNotBetween(Date value1, Date value2) {
            addCriterion("gmt_modified not between", value1, value2, "gmtModified");
            return (Criteria) this;
        }

        public Criteria andPayOrderNoIsNull() {
            addCriterion("pay_order_no is null");
            return (Criteria) this;
        }

        public Criteria andPayOrderNoIsNotNull() {
            addCriterion("pay_order_no is not null");
            return (Criteria) this;
        }

        public Criteria andPayOrderNoEqualTo(Long value) {
            addCriterion("pay_order_no =", value, "payOrderNo");
            return (Criteria) this;
        }

        public Criteria andPayOrderNoNotEqualTo(Long value) {
            addCriterion("pay_order_no <>", value, "payOrderNo");
            return (Criteria) this;
        }

        public Criteria andPayOrderNoGreaterThan(Long value) {
            addCriterion("pay_order_no >", value, "payOrderNo");
            return (Criteria) this;
        }

        public Criteria andPayOrderNoGreaterThanOrEqualTo(Long value) {
            addCriterion("pay_order_no >=", value, "payOrderNo");
            return (Criteria) this;
        }

        public Criteria andPayOrderNoLessThan(Long value) {
            addCriterion("pay_order_no <", value, "payOrderNo");
            return (Criteria) this;
        }

        public Criteria andPayOrderNoLessThanOrEqualTo(Long value) {
            addCriterion("pay_order_no <=", value, "payOrderNo");
            return (Criteria) this;
        }

        public Criteria andPayOrderNoIn(List<Long> values) {
            addCriterion("pay_order_no in", values, "payOrderNo");
            return (Criteria) this;
        }

        public Criteria andPayOrderNoNotIn(List<Long> values) {
            addCriterion("pay_order_no not in", values, "payOrderNo");
            return (Criteria) this;
        }

        public Criteria andPayOrderNoBetween(Long value1, Long value2) {
            addCriterion("pay_order_no between", value1, value2, "payOrderNo");
            return (Criteria) this;
        }

        public Criteria andPayOrderNoNotBetween(Long value1, Long value2) {
            addCriterion("pay_order_no not between", value1, value2, "payOrderNo");
            return (Criteria) this;
        }

        public Criteria andSysCodeIsNull() {
            addCriterion("sys_code is null");
            return (Criteria) this;
        }

        public Criteria andSysCodeIsNotNull() {
            addCriterion("sys_code is not null");
            return (Criteria) this;
        }

        public Criteria andSysCodeEqualTo(String value) {
            addCriterion("sys_code =", value, "sysCode");
            return (Criteria) this;
        }

        public Criteria andSysCodeNotEqualTo(String value) {
            addCriterion("sys_code <>", value, "sysCode");
            return (Criteria) this;
        }

        public Criteria andSysCodeGreaterThan(String value) {
            addCriterion("sys_code >", value, "sysCode");
            return (Criteria) this;
        }

        public Criteria andSysCodeGreaterThanOrEqualTo(String value) {
            addCriterion("sys_code >=", value, "sysCode");
            return (Criteria) this;
        }

        public Criteria andSysCodeLessThan(String value) {
            addCriterion("sys_code <", value, "sysCode");
            return (Criteria) this;
        }

        public Criteria andSysCodeLessThanOrEqualTo(String value) {
            addCriterion("sys_code <=", value, "sysCode");
            return (Criteria) this;
        }

        public Criteria andSysCodeLike(String value) {
            addCriterion("sys_code like", value, "sysCode");
            return (Criteria) this;
        }

        public Criteria andSysCodeNotLike(String value) {
            addCriterion("sys_code not like", value, "sysCode");
            return (Criteria) this;
        }

        public Criteria andSysCodeIn(List<String> values) {
            addCriterion("sys_code in", values, "sysCode");
            return (Criteria) this;
        }

        public Criteria andSysCodeNotIn(List<String> values) {
            addCriterion("sys_code not in", values, "sysCode");
            return (Criteria) this;
        }

        public Criteria andSysCodeBetween(String value1, String value2) {
            addCriterion("sys_code between", value1, value2, "sysCode");
            return (Criteria) this;
        }

        public Criteria andSysCodeNotBetween(String value1, String value2) {
            addCriterion("sys_code not between", value1, value2, "sysCode");
            return (Criteria) this;
        }

        public Criteria andBizIdentifyNoIsNull() {
            addCriterion("biz_identify_no is null");
            return (Criteria) this;
        }

        public Criteria andBizIdentifyNoIsNotNull() {
            addCriterion("biz_identify_no is not null");
            return (Criteria) this;
        }

        public Criteria andBizIdentifyNoEqualTo(String value) {
            addCriterion("biz_identify_no =", value, "bizIdentifyNo");
            return (Criteria) this;
        }

        public Criteria andBizIdentifyNoNotEqualTo(String value) {
            addCriterion("biz_identify_no <>", value, "bizIdentifyNo");
            return (Criteria) this;
        }

        public Criteria andBizIdentifyNoGreaterThan(String value) {
            addCriterion("biz_identify_no >", value, "bizIdentifyNo");
            return (Criteria) this;
        }

        public Criteria andBizIdentifyNoGreaterThanOrEqualTo(String value) {
            addCriterion("biz_identify_no >=", value, "bizIdentifyNo");
            return (Criteria) this;
        }

        public Criteria andBizIdentifyNoLessThan(String value) {
            addCriterion("biz_identify_no <", value, "bizIdentifyNo");
            return (Criteria) this;
        }

        public Criteria andBizIdentifyNoLessThanOrEqualTo(String value) {
            addCriterion("biz_identify_no <=", value, "bizIdentifyNo");
            return (Criteria) this;
        }

        public Criteria andBizIdentifyNoLike(String value) {
            addCriterion("biz_identify_no like", value, "bizIdentifyNo");
            return (Criteria) this;
        }

        public Criteria andBizIdentifyNoNotLike(String value) {
            addCriterion("biz_identify_no not like", value, "bizIdentifyNo");
            return (Criteria) this;
        }

        public Criteria andBizIdentifyNoIn(List<String> values) {
            addCriterion("biz_identify_no in", values, "bizIdentifyNo");
            return (Criteria) this;
        }

        public Criteria andBizIdentifyNoNotIn(List<String> values) {
            addCriterion("biz_identify_no not in", values, "bizIdentifyNo");
            return (Criteria) this;
        }

        public Criteria andBizIdentifyNoBetween(String value1, String value2) {
            addCriterion("biz_identify_no between", value1, value2, "bizIdentifyNo");
            return (Criteria) this;
        }

        public Criteria andBizIdentifyNoNotBetween(String value1, String value2) {
            addCriterion("biz_identify_no not between", value1, value2, "bizIdentifyNo");
            return (Criteria) this;
        }

        public Criteria andBizUniqueNoIsNull() {
            addCriterion("biz_unique_no is null");
            return (Criteria) this;
        }

        public Criteria andBizUniqueNoIsNotNull() {
            addCriterion("biz_unique_no is not null");
            return (Criteria) this;
        }

        public Criteria andBizUniqueNoEqualTo(String value) {
            addCriterion("biz_unique_no =", value, "bizUniqueNo");
            return (Criteria) this;
        }

        public Criteria andBizUniqueNoNotEqualTo(String value) {
            addCriterion("biz_unique_no <>", value, "bizUniqueNo");
            return (Criteria) this;
        }

        public Criteria andBizUniqueNoGreaterThan(String value) {
            addCriterion("biz_unique_no >", value, "bizUniqueNo");
            return (Criteria) this;
        }

        public Criteria andBizUniqueNoGreaterThanOrEqualTo(String value) {
            addCriterion("biz_unique_no >=", value, "bizUniqueNo");
            return (Criteria) this;
        }

        public Criteria andBizUniqueNoLessThan(String value) {
            addCriterion("biz_unique_no <", value, "bizUniqueNo");
            return (Criteria) this;
        }

        public Criteria andBizUniqueNoLessThanOrEqualTo(String value) {
            addCriterion("biz_unique_no <=", value, "bizUniqueNo");
            return (Criteria) this;
        }

        public Criteria andBizUniqueNoLike(String value) {
            addCriterion("biz_unique_no like", value, "bizUniqueNo");
            return (Criteria) this;
        }

        public Criteria andBizUniqueNoNotLike(String value) {
            addCriterion("biz_unique_no not like", value, "bizUniqueNo");
            return (Criteria) this;
        }

        public Criteria andBizUniqueNoIn(List<String> values) {
            addCriterion("biz_unique_no in", values, "bizUniqueNo");
            return (Criteria) this;
        }

        public Criteria andBizUniqueNoNotIn(List<String> values) {
            addCriterion("biz_unique_no not in", values, "bizUniqueNo");
            return (Criteria) this;
        }

        public Criteria andBizUniqueNoBetween(String value1, String value2) {
            addCriterion("biz_unique_no between", value1, value2, "bizUniqueNo");
            return (Criteria) this;
        }

        public Criteria andBizUniqueNoNotBetween(String value1, String value2) {
            addCriterion("biz_unique_no not between", value1, value2, "bizUniqueNo");
            return (Criteria) this;
        }

        public Criteria andMoneyIsNull() {
            addCriterion("money is null");
            return (Criteria) this;
        }

        public Criteria andMoneyIsNotNull() {
            addCriterion("money is not null");
            return (Criteria) this;
        }

        public Criteria andMoneyEqualTo(Long value) {
            addCriterion("money =", value, "money");
            return (Criteria) this;
        }

        public Criteria andMoneyNotEqualTo(Long value) {
            addCriterion("money <>", value, "money");
            return (Criteria) this;
        }

        public Criteria andMoneyGreaterThan(Long value) {
            addCriterion("money >", value, "money");
            return (Criteria) this;
        }

        public Criteria andMoneyGreaterThanOrEqualTo(Long value) {
            addCriterion("money >=", value, "money");
            return (Criteria) this;
        }

        public Criteria andMoneyLessThan(Long value) {
            addCriterion("money <", value, "money");
            return (Criteria) this;
        }

        public Criteria andMoneyLessThanOrEqualTo(Long value) {
            addCriterion("money <=", value, "money");
            return (Criteria) this;
        }

        public Criteria andMoneyIn(List<Long> values) {
            addCriterion("money in", values, "money");
            return (Criteria) this;
        }

        public Criteria andMoneyNotIn(List<Long> values) {
            addCriterion("money not in", values, "money");
            return (Criteria) this;
        }

        public Criteria andMoneyBetween(Long value1, Long value2) {
            addCriterion("money between", value1, value2, "money");
            return (Criteria) this;
        }

        public Criteria andMoneyNotBetween(Long value1, Long value2) {
            addCriterion("money not between", value1, value2, "money");
            return (Criteria) this;
        }

        public Criteria andPayChannelTypeIsNull() {
            addCriterion("pay_channel_type is null");
            return (Criteria) this;
        }

        public Criteria andPayChannelTypeIsNotNull() {
            addCriterion("pay_channel_type is not null");
            return (Criteria) this;
        }

        public Criteria andPayChannelTypeEqualTo(Integer value) {
            addCriterion("pay_channel_type =", value, "payChannelType");
            return (Criteria) this;
        }

        public Criteria andPayChannelTypeNotEqualTo(Integer value) {
            addCriterion("pay_channel_type <>", value, "payChannelType");
            return (Criteria) this;
        }

        public Criteria andPayChannelTypeGreaterThan(Integer value) {
            addCriterion("pay_channel_type >", value, "payChannelType");
            return (Criteria) this;
        }

        public Criteria andPayChannelTypeGreaterThanOrEqualTo(Integer value) {
            addCriterion("pay_channel_type >=", value, "payChannelType");
            return (Criteria) this;
        }

        public Criteria andPayChannelTypeLessThan(Integer value) {
            addCriterion("pay_channel_type <", value, "payChannelType");
            return (Criteria) this;
        }

        public Criteria andPayChannelTypeLessThanOrEqualTo(Integer value) {
            addCriterion("pay_channel_type <=", value, "payChannelType");
            return (Criteria) this;
        }

        public Criteria andPayChannelTypeIn(List<Integer> values) {
            addCriterion("pay_channel_type in", values, "payChannelType");
            return (Criteria) this;
        }

        public Criteria andPayChannelTypeNotIn(List<Integer> values) {
            addCriterion("pay_channel_type not in", values, "payChannelType");
            return (Criteria) this;
        }

        public Criteria andPayChannelTypeBetween(Integer value1, Integer value2) {
            addCriterion("pay_channel_type between", value1, value2, "payChannelType");
            return (Criteria) this;
        }

        public Criteria andPayChannelTypeNotBetween(Integer value1, Integer value2) {
            addCriterion("pay_channel_type not between", value1, value2, "payChannelType");
            return (Criteria) this;
        }

        public Criteria andTargetAccountTypeIsNull() {
            addCriterion("target_account_type is null");
            return (Criteria) this;
        }

        public Criteria andTargetAccountTypeIsNotNull() {
            addCriterion("target_account_type is not null");
            return (Criteria) this;
        }

        public Criteria andTargetAccountTypeEqualTo(Integer value) {
            addCriterion("target_account_type =", value, "targetAccountType");
            return (Criteria) this;
        }

        public Criteria andTargetAccountTypeNotEqualTo(Integer value) {
            addCriterion("target_account_type <>", value, "targetAccountType");
            return (Criteria) this;
        }

        public Criteria andTargetAccountTypeGreaterThan(Integer value) {
            addCriterion("target_account_type >", value, "targetAccountType");
            return (Criteria) this;
        }

        public Criteria andTargetAccountTypeGreaterThanOrEqualTo(Integer value) {
            addCriterion("target_account_type >=", value, "targetAccountType");
            return (Criteria) this;
        }

        public Criteria andTargetAccountTypeLessThan(Integer value) {
            addCriterion("target_account_type <", value, "targetAccountType");
            return (Criteria) this;
        }

        public Criteria andTargetAccountTypeLessThanOrEqualTo(Integer value) {
            addCriterion("target_account_type <=", value, "targetAccountType");
            return (Criteria) this;
        }

        public Criteria andTargetAccountTypeIn(List<Integer> values) {
            addCriterion("target_account_type in", values, "targetAccountType");
            return (Criteria) this;
        }

        public Criteria andTargetAccountTypeNotIn(List<Integer> values) {
            addCriterion("target_account_type not in", values, "targetAccountType");
            return (Criteria) this;
        }

        public Criteria andTargetAccountTypeBetween(Integer value1, Integer value2) {
            addCriterion("target_account_type between", value1, value2, "targetAccountType");
            return (Criteria) this;
        }

        public Criteria andTargetAccountTypeNotBetween(Integer value1, Integer value2) {
            addCriterion("target_account_type not between", value1, value2, "targetAccountType");
            return (Criteria) this;
        }

        public Criteria andAccountingEntryIsNull() {
            addCriterion("accounting_entry is null");
            return (Criteria) this;
        }

        public Criteria andAccountingEntryIsNotNull() {
            addCriterion("accounting_entry is not null");
            return (Criteria) this;
        }

        public Criteria andAccountingEntryEqualTo(Integer value) {
            addCriterion("accounting_entry =", value, "accountingEntry");
            return (Criteria) this;
        }

        public Criteria andAccountingEntryNotEqualTo(Integer value) {
            addCriterion("accounting_entry <>", value, "accountingEntry");
            return (Criteria) this;
        }

        public Criteria andAccountingEntryGreaterThan(Integer value) {
            addCriterion("accounting_entry >", value, "accountingEntry");
            return (Criteria) this;
        }

        public Criteria andAccountingEntryGreaterThanOrEqualTo(Integer value) {
            addCriterion("accounting_entry >=", value, "accountingEntry");
            return (Criteria) this;
        }

        public Criteria andAccountingEntryLessThan(Integer value) {
            addCriterion("accounting_entry <", value, "accountingEntry");
            return (Criteria) this;
        }

        public Criteria andAccountingEntryLessThanOrEqualTo(Integer value) {
            addCriterion("accounting_entry <=", value, "accountingEntry");
            return (Criteria) this;
        }

        public Criteria andAccountingEntryIn(List<Integer> values) {
            addCriterion("accounting_entry in", values, "accountingEntry");
            return (Criteria) this;
        }

        public Criteria andAccountingEntryNotIn(List<Integer> values) {
            addCriterion("accounting_entry not in", values, "accountingEntry");
            return (Criteria) this;
        }

        public Criteria andAccountingEntryBetween(Integer value1, Integer value2) {
            addCriterion("accounting_entry between", value1, value2, "accountingEntry");
            return (Criteria) this;
        }

        public Criteria andAccountingEntryNotBetween(Integer value1, Integer value2) {
            addCriterion("accounting_entry not between", value1, value2, "accountingEntry");
            return (Criteria) this;
        }

        public Criteria andGmtAcceptedTimeIsNull() {
            addCriterion("gmt_accepted_time is null");
            return (Criteria) this;
        }

        public Criteria andGmtAcceptedTimeIsNotNull() {
            addCriterion("gmt_accepted_time is not null");
            return (Criteria) this;
        }

        public Criteria andGmtAcceptedTimeEqualTo(Date value) {
            addCriterion("gmt_accepted_time =", value, "gmtAcceptedTime");
            return (Criteria) this;
        }

        public Criteria andGmtAcceptedTimeNotEqualTo(Date value) {
            addCriterion("gmt_accepted_time <>", value, "gmtAcceptedTime");
            return (Criteria) this;
        }

        public Criteria andGmtAcceptedTimeGreaterThan(Date value) {
            addCriterion("gmt_accepted_time >", value, "gmtAcceptedTime");
            return (Criteria) this;
        }

        public Criteria andGmtAcceptedTimeGreaterThanOrEqualTo(Date value) {
            addCriterion("gmt_accepted_time >=", value, "gmtAcceptedTime");
            return (Criteria) this;
        }

        public Criteria andGmtAcceptedTimeLessThan(Date value) {
            addCriterion("gmt_accepted_time <", value, "gmtAcceptedTime");
            return (Criteria) this;
        }

        public Criteria andGmtAcceptedTimeLessThanOrEqualTo(Date value) {
            addCriterion("gmt_accepted_time <=", value, "gmtAcceptedTime");
            return (Criteria) this;
        }

        public Criteria andGmtAcceptedTimeIn(List<Date> values) {
            addCriterion("gmt_accepted_time in", values, "gmtAcceptedTime");
            return (Criteria) this;
        }

        public Criteria andGmtAcceptedTimeNotIn(List<Date> values) {
            addCriterion("gmt_accepted_time not in", values, "gmtAcceptedTime");
            return (Criteria) this;
        }

        public Criteria andGmtAcceptedTimeBetween(Date value1, Date value2) {
            addCriterion("gmt_accepted_time between", value1, value2, "gmtAcceptedTime");
            return (Criteria) this;
        }

        public Criteria andGmtAcceptedTimeNotBetween(Date value1, Date value2) {
            addCriterion("gmt_accepted_time not between", value1, value2, "gmtAcceptedTime");
            return (Criteria) this;
        }

        public Criteria andGmtPaymentBeginTimeIsNull() {
            addCriterion("gmt_payment_begin_time is null");
            return (Criteria) this;
        }

        public Criteria andGmtPaymentBeginTimeIsNotNull() {
            addCriterion("gmt_payment_begin_time is not null");
            return (Criteria) this;
        }

        public Criteria andGmtPaymentBeginTimeEqualTo(Date value) {
            addCriterion("gmt_payment_begin_time =", value, "gmtPaymentBeginTime");
            return (Criteria) this;
        }

        public Criteria andGmtPaymentBeginTimeNotEqualTo(Date value) {
            addCriterion("gmt_payment_begin_time <>", value, "gmtPaymentBeginTime");
            return (Criteria) this;
        }

        public Criteria andGmtPaymentBeginTimeGreaterThan(Date value) {
            addCriterion("gmt_payment_begin_time >", value, "gmtPaymentBeginTime");
            return (Criteria) this;
        }

        public Criteria andGmtPaymentBeginTimeGreaterThanOrEqualTo(Date value) {
            addCriterion("gmt_payment_begin_time >=", value, "gmtPaymentBeginTime");
            return (Criteria) this;
        }

        public Criteria andGmtPaymentBeginTimeLessThan(Date value) {
            addCriterion("gmt_payment_begin_time <", value, "gmtPaymentBeginTime");
            return (Criteria) this;
        }

        public Criteria andGmtPaymentBeginTimeLessThanOrEqualTo(Date value) {
            addCriterion("gmt_payment_begin_time <=", value, "gmtPaymentBeginTime");
            return (Criteria) this;
        }

        public Criteria andGmtPaymentBeginTimeIn(List<Date> values) {
            addCriterion("gmt_payment_begin_time in", values, "gmtPaymentBeginTime");
            return (Criteria) this;
        }

        public Criteria andGmtPaymentBeginTimeNotIn(List<Date> values) {
            addCriterion("gmt_payment_begin_time not in", values, "gmtPaymentBeginTime");
            return (Criteria) this;
        }

        public Criteria andGmtPaymentBeginTimeBetween(Date value1, Date value2) {
            addCriterion("gmt_payment_begin_time between", value1, value2, "gmtPaymentBeginTime");
            return (Criteria) this;
        }

        public Criteria andGmtPaymentBeginTimeNotBetween(Date value1, Date value2) {
            addCriterion("gmt_payment_begin_time not between", value1, value2, "gmtPaymentBeginTime");
            return (Criteria) this;
        }

        public Criteria andGmtPaymentSuccessTimeIsNull() {
            addCriterion("gmt_payment_success_time is null");
            return (Criteria) this;
        }

        public Criteria andGmtPaymentSuccessTimeIsNotNull() {
            addCriterion("gmt_payment_success_time is not null");
            return (Criteria) this;
        }

        public Criteria andGmtPaymentSuccessTimeEqualTo(Date value) {
            addCriterion("gmt_payment_success_time =", value, "gmtPaymentSuccessTime");
            return (Criteria) this;
        }

        public Criteria andGmtPaymentSuccessTimeNotEqualTo(Date value) {
            addCriterion("gmt_payment_success_time <>", value, "gmtPaymentSuccessTime");
            return (Criteria) this;
        }

        public Criteria andGmtPaymentSuccessTimeGreaterThan(Date value) {
            addCriterion("gmt_payment_success_time >", value, "gmtPaymentSuccessTime");
            return (Criteria) this;
        }

        public Criteria andGmtPaymentSuccessTimeGreaterThanOrEqualTo(Date value) {
            addCriterion("gmt_payment_success_time >=", value, "gmtPaymentSuccessTime");
            return (Criteria) this;
        }

        public Criteria andGmtPaymentSuccessTimeLessThan(Date value) {
            addCriterion("gmt_payment_success_time <", value, "gmtPaymentSuccessTime");
            return (Criteria) this;
        }

        public Criteria andGmtPaymentSuccessTimeLessThanOrEqualTo(Date value) {
            addCriterion("gmt_payment_success_time <=", value, "gmtPaymentSuccessTime");
            return (Criteria) this;
        }

        public Criteria andGmtPaymentSuccessTimeIn(List<Date> values) {
            addCriterion("gmt_payment_success_time in", values, "gmtPaymentSuccessTime");
            return (Criteria) this;
        }

        public Criteria andGmtPaymentSuccessTimeNotIn(List<Date> values) {
            addCriterion("gmt_payment_success_time not in", values, "gmtPaymentSuccessTime");
            return (Criteria) this;
        }

        public Criteria andGmtPaymentSuccessTimeBetween(Date value1, Date value2) {
            addCriterion("gmt_payment_success_time between", value1, value2, "gmtPaymentSuccessTime");
            return (Criteria) this;
        }

        public Criteria andGmtPaymentSuccessTimeNotBetween(Date value1, Date value2) {
            addCriterion("gmt_payment_success_time not between", value1, value2, "gmtPaymentSuccessTime");
            return (Criteria) this;
        }

        public Criteria andGmtPaymentFailureTimeIsNull() {
            addCriterion("gmt_payment_failure_time is null");
            return (Criteria) this;
        }

        public Criteria andGmtPaymentFailureTimeIsNotNull() {
            addCriterion("gmt_payment_failure_time is not null");
            return (Criteria) this;
        }

        public Criteria andGmtPaymentFailureTimeEqualTo(Date value) {
            addCriterion("gmt_payment_failure_time =", value, "gmtPaymentFailureTime");
            return (Criteria) this;
        }

        public Criteria andGmtPaymentFailureTimeNotEqualTo(Date value) {
            addCriterion("gmt_payment_failure_time <>", value, "gmtPaymentFailureTime");
            return (Criteria) this;
        }

        public Criteria andGmtPaymentFailureTimeGreaterThan(Date value) {
            addCriterion("gmt_payment_failure_time >", value, "gmtPaymentFailureTime");
            return (Criteria) this;
        }

        public Criteria andGmtPaymentFailureTimeGreaterThanOrEqualTo(Date value) {
            addCriterion("gmt_payment_failure_time >=", value, "gmtPaymentFailureTime");
            return (Criteria) this;
        }

        public Criteria andGmtPaymentFailureTimeLessThan(Date value) {
            addCriterion("gmt_payment_failure_time <", value, "gmtPaymentFailureTime");
            return (Criteria) this;
        }

        public Criteria andGmtPaymentFailureTimeLessThanOrEqualTo(Date value) {
            addCriterion("gmt_payment_failure_time <=", value, "gmtPaymentFailureTime");
            return (Criteria) this;
        }

        public Criteria andGmtPaymentFailureTimeIn(List<Date> values) {
            addCriterion("gmt_payment_failure_time in", values, "gmtPaymentFailureTime");
            return (Criteria) this;
        }

        public Criteria andGmtPaymentFailureTimeNotIn(List<Date> values) {
            addCriterion("gmt_payment_failure_time not in", values, "gmtPaymentFailureTime");
            return (Criteria) this;
        }

        public Criteria andGmtPaymentFailureTimeBetween(Date value1, Date value2) {
            addCriterion("gmt_payment_failure_time between", value1, value2, "gmtPaymentFailureTime");
            return (Criteria) this;
        }

        public Criteria andGmtPaymentFailureTimeNotBetween(Date value1, Date value2) {
            addCriterion("gmt_payment_failure_time not between", value1, value2, "gmtPaymentFailureTime");
            return (Criteria) this;
        }

        public Criteria andGmtPaymentClosedTimeIsNull() {
            addCriterion("gmt_payment_closed_time is null");
            return (Criteria) this;
        }

        public Criteria andGmtPaymentClosedTimeIsNotNull() {
            addCriterion("gmt_payment_closed_time is not null");
            return (Criteria) this;
        }

        public Criteria andGmtPaymentClosedTimeEqualTo(Date value) {
            addCriterion("gmt_payment_closed_time =", value, "gmtPaymentClosedTime");
            return (Criteria) this;
        }

        public Criteria andGmtPaymentClosedTimeNotEqualTo(Date value) {
            addCriterion("gmt_payment_closed_time <>", value, "gmtPaymentClosedTime");
            return (Criteria) this;
        }

        public Criteria andGmtPaymentClosedTimeGreaterThan(Date value) {
            addCriterion("gmt_payment_closed_time >", value, "gmtPaymentClosedTime");
            return (Criteria) this;
        }

        public Criteria andGmtPaymentClosedTimeGreaterThanOrEqualTo(Date value) {
            addCriterion("gmt_payment_closed_time >=", value, "gmtPaymentClosedTime");
            return (Criteria) this;
        }

        public Criteria andGmtPaymentClosedTimeLessThan(Date value) {
            addCriterion("gmt_payment_closed_time <", value, "gmtPaymentClosedTime");
            return (Criteria) this;
        }

        public Criteria andGmtPaymentClosedTimeLessThanOrEqualTo(Date value) {
            addCriterion("gmt_payment_closed_time <=", value, "gmtPaymentClosedTime");
            return (Criteria) this;
        }

        public Criteria andGmtPaymentClosedTimeIn(List<Date> values) {
            addCriterion("gmt_payment_closed_time in", values, "gmtPaymentClosedTime");
            return (Criteria) this;
        }

        public Criteria andGmtPaymentClosedTimeNotIn(List<Date> values) {
            addCriterion("gmt_payment_closed_time not in", values, "gmtPaymentClosedTime");
            return (Criteria) this;
        }

        public Criteria andGmtPaymentClosedTimeBetween(Date value1, Date value2) {
            addCriterion("gmt_payment_closed_time between", value1, value2, "gmtPaymentClosedTime");
            return (Criteria) this;
        }

        public Criteria andGmtPaymentClosedTimeNotBetween(Date value1, Date value2) {
            addCriterion("gmt_payment_closed_time not between", value1, value2, "gmtPaymentClosedTime");
            return (Criteria) this;
        }

        public Criteria andGmtPaymentBouncedTimeIsNull() {
            addCriterion("gmt_payment_bounced_time is null");
            return (Criteria) this;
        }

        public Criteria andGmtPaymentBouncedTimeIsNotNull() {
            addCriterion("gmt_payment_bounced_time is not null");
            return (Criteria) this;
        }

        public Criteria andGmtPaymentBouncedTimeEqualTo(Date value) {
            addCriterion("gmt_payment_bounced_time =", value, "gmtPaymentBouncedTime");
            return (Criteria) this;
        }

        public Criteria andGmtPaymentBouncedTimeNotEqualTo(Date value) {
            addCriterion("gmt_payment_bounced_time <>", value, "gmtPaymentBouncedTime");
            return (Criteria) this;
        }

        public Criteria andGmtPaymentBouncedTimeGreaterThan(Date value) {
            addCriterion("gmt_payment_bounced_time >", value, "gmtPaymentBouncedTime");
            return (Criteria) this;
        }

        public Criteria andGmtPaymentBouncedTimeGreaterThanOrEqualTo(Date value) {
            addCriterion("gmt_payment_bounced_time >=", value, "gmtPaymentBouncedTime");
            return (Criteria) this;
        }

        public Criteria andGmtPaymentBouncedTimeLessThan(Date value) {
            addCriterion("gmt_payment_bounced_time <", value, "gmtPaymentBouncedTime");
            return (Criteria) this;
        }

        public Criteria andGmtPaymentBouncedTimeLessThanOrEqualTo(Date value) {
            addCriterion("gmt_payment_bounced_time <=", value, "gmtPaymentBouncedTime");
            return (Criteria) this;
        }

        public Criteria andGmtPaymentBouncedTimeIn(List<Date> values) {
            addCriterion("gmt_payment_bounced_time in", values, "gmtPaymentBouncedTime");
            return (Criteria) this;
        }

        public Criteria andGmtPaymentBouncedTimeNotIn(List<Date> values) {
            addCriterion("gmt_payment_bounced_time not in", values, "gmtPaymentBouncedTime");
            return (Criteria) this;
        }

        public Criteria andGmtPaymentBouncedTimeBetween(Date value1, Date value2) {
            addCriterion("gmt_payment_bounced_time between", value1, value2, "gmtPaymentBouncedTime");
            return (Criteria) this;
        }

        public Criteria andGmtPaymentBouncedTimeNotBetween(Date value1, Date value2) {
            addCriterion("gmt_payment_bounced_time not between", value1, value2, "gmtPaymentBouncedTime");
            return (Criteria) this;
        }

        public Criteria andStatusIsNull() {
            addCriterion("status is null");
            return (Criteria) this;
        }

        public Criteria andStatusIsNotNull() {
            addCriterion("status is not null");
            return (Criteria) this;
        }

        public Criteria andStatusEqualTo(Integer value) {
            addCriterion("status =", value, "status");
            return (Criteria) this;
        }

        public Criteria andStatusNotEqualTo(Integer value) {
            addCriterion("status <>", value, "status");
            return (Criteria) this;
        }

        public Criteria andStatusGreaterThan(Integer value) {
            addCriterion("status >", value, "status");
            return (Criteria) this;
        }

        public Criteria andStatusGreaterThanOrEqualTo(Integer value) {
            addCriterion("status >=", value, "status");
            return (Criteria) this;
        }

        public Criteria andStatusLessThan(Integer value) {
            addCriterion("status <", value, "status");
            return (Criteria) this;
        }

        public Criteria andStatusLessThanOrEqualTo(Integer value) {
            addCriterion("status <=", value, "status");
            return (Criteria) this;
        }

        public Criteria andStatusIn(List<Integer> values) {
            addCriterion("status in", values, "status");
            return (Criteria) this;
        }

        public Criteria andStatusNotIn(List<Integer> values) {
            addCriterion("status not in", values, "status");
            return (Criteria) this;
        }

        public Criteria andStatusBetween(Integer value1, Integer value2) {
            addCriterion("status between", value1, value2, "status");
            return (Criteria) this;
        }

        public Criteria andStatusNotBetween(Integer value1, Integer value2) {
            addCriterion("status not between", value1, value2, "status");
            return (Criteria) this;
        }

        public Criteria andVersionIsNull() {
            addCriterion("version is null");
            return (Criteria) this;
        }

        public Criteria andVersionIsNotNull() {
            addCriterion("version is not null");
            return (Criteria) this;
        }

        public Criteria andVersionEqualTo(Integer value) {
            addCriterion("version =", value, "version");
            return (Criteria) this;
        }

        public Criteria andVersionNotEqualTo(Integer value) {
            addCriterion("version <>", value, "version");
            return (Criteria) this;
        }

        public Criteria andVersionGreaterThan(Integer value) {
            addCriterion("version >", value, "version");
            return (Criteria) this;
        }

        public Criteria andVersionGreaterThanOrEqualTo(Integer value) {
            addCriterion("version >=", value, "version");
            return (Criteria) this;
        }

        public Criteria andVersionLessThan(Integer value) {
            addCriterion("version <", value, "version");
            return (Criteria) this;
        }

        public Criteria andVersionLessThanOrEqualTo(Integer value) {
            addCriterion("version <=", value, "version");
            return (Criteria) this;
        }

        public Criteria andVersionIn(List<Integer> values) {
            addCriterion("version in", values, "version");
            return (Criteria) this;
        }

        public Criteria andVersionNotIn(List<Integer> values) {
            addCriterion("version not in", values, "version");
            return (Criteria) this;
        }

        public Criteria andVersionBetween(Integer value1, Integer value2) {
            addCriterion("version between", value1, value2, "version");
            return (Criteria) this;
        }

        public Criteria andVersionNotBetween(Integer value1, Integer value2) {
            addCriterion("version not between", value1, value2, "version");
            return (Criteria) this;
        }

        public Criteria andMemoIsNull() {
            addCriterion("memo is null");
            return (Criteria) this;
        }

        public Criteria andMemoIsNotNull() {
            addCriterion("memo is not null");
            return (Criteria) this;
        }

        public Criteria andMemoEqualTo(String value) {
            addCriterion("memo =", value, "memo");
            return (Criteria) this;
        }

        public Criteria andMemoNotEqualTo(String value) {
            addCriterion("memo <>", value, "memo");
            return (Criteria) this;
        }

        public Criteria andMemoGreaterThan(String value) {
            addCriterion("memo >", value, "memo");
            return (Criteria) this;
        }

        public Criteria andMemoGreaterThanOrEqualTo(String value) {
            addCriterion("memo >=", value, "memo");
            return (Criteria) this;
        }

        public Criteria andMemoLessThan(String value) {
            addCriterion("memo <", value, "memo");
            return (Criteria) this;
        }

        public Criteria andMemoLessThanOrEqualTo(String value) {
            addCriterion("memo <=", value, "memo");
            return (Criteria) this;
        }

        public Criteria andMemoLike(String value) {
            addCriterion("memo like", value, "memo");
            return (Criteria) this;
        }

        public Criteria andMemoNotLike(String value) {
            addCriterion("memo not like", value, "memo");
            return (Criteria) this;
        }

        public Criteria andMemoIn(List<String> values) {
            addCriterion("memo in", values, "memo");
            return (Criteria) this;
        }

        public Criteria andMemoNotIn(List<String> values) {
            addCriterion("memo not in", values, "memo");
            return (Criteria) this;
        }

        public Criteria andMemoBetween(String value1, String value2) {
            addCriterion("memo between", value1, value2, "memo");
            return (Criteria) this;
        }

        public Criteria andMemoNotBetween(String value1, String value2) {
            addCriterion("memo not between", value1, value2, "memo");
            return (Criteria) this;
        }

        public Criteria andChannelPaymentTraceNoIsNull() {
            addCriterion("channel_payment_trace_no is null");
            return (Criteria) this;
        }

        public Criteria andChannelPaymentTraceNoIsNotNull() {
            addCriterion("channel_payment_trace_no is not null");
            return (Criteria) this;
        }

        public Criteria andChannelPaymentTraceNoEqualTo(String value) {
            addCriterion("channel_payment_trace_no =", value, "channelPaymentTraceNo");
            return (Criteria) this;
        }

        public Criteria andChannelPaymentTraceNoNotEqualTo(String value) {
            addCriterion("channel_payment_trace_no <>", value, "channelPaymentTraceNo");
            return (Criteria) this;
        }

        public Criteria andChannelPaymentTraceNoGreaterThan(String value) {
            addCriterion("channel_payment_trace_no >", value, "channelPaymentTraceNo");
            return (Criteria) this;
        }

        public Criteria andChannelPaymentTraceNoGreaterThanOrEqualTo(String value) {
            addCriterion("channel_payment_trace_no >=", value, "channelPaymentTraceNo");
            return (Criteria) this;
        }

        public Criteria andChannelPaymentTraceNoLessThan(String value) {
            addCriterion("channel_payment_trace_no <", value, "channelPaymentTraceNo");
            return (Criteria) this;
        }

        public Criteria andChannelPaymentTraceNoLessThanOrEqualTo(String value) {
            addCriterion("channel_payment_trace_no <=", value, "channelPaymentTraceNo");
            return (Criteria) this;
        }

        public Criteria andChannelPaymentTraceNoLike(String value) {
            addCriterion("channel_payment_trace_no like", value, "channelPaymentTraceNo");
            return (Criteria) this;
        }

        public Criteria andChannelPaymentTraceNoNotLike(String value) {
            addCriterion("channel_payment_trace_no not like", value, "channelPaymentTraceNo");
            return (Criteria) this;
        }

        public Criteria andChannelPaymentTraceNoIn(List<String> values) {
            addCriterion("channel_payment_trace_no in", values, "channelPaymentTraceNo");
            return (Criteria) this;
        }

        public Criteria andChannelPaymentTraceNoNotIn(List<String> values) {
            addCriterion("channel_payment_trace_no not in", values, "channelPaymentTraceNo");
            return (Criteria) this;
        }

        public Criteria andChannelPaymentTraceNoBetween(String value1, String value2) {
            addCriterion("channel_payment_trace_no between", value1, value2, "channelPaymentTraceNo");
            return (Criteria) this;
        }

        public Criteria andChannelPaymentTraceNoNotBetween(String value1, String value2) {
            addCriterion("channel_payment_trace_no not between", value1, value2, "channelPaymentTraceNo");
            return (Criteria) this;
        }

        public Criteria andChannelDishonorTraceNoIsNull() {
            addCriterion("channel_dishonor_trace_no is null");
            return (Criteria) this;
        }

        public Criteria andChannelDishonorTraceNoIsNotNull() {
            addCriterion("channel_dishonor_trace_no is not null");
            return (Criteria) this;
        }

        public Criteria andChannelDishonorTraceNoEqualTo(String value) {
            addCriterion("channel_dishonor_trace_no =", value, "channelDishonorTraceNo");
            return (Criteria) this;
        }

        public Criteria andChannelDishonorTraceNoNotEqualTo(String value) {
            addCriterion("channel_dishonor_trace_no <>", value, "channelDishonorTraceNo");
            return (Criteria) this;
        }

        public Criteria andChannelDishonorTraceNoGreaterThan(String value) {
            addCriterion("channel_dishonor_trace_no >", value, "channelDishonorTraceNo");
            return (Criteria) this;
        }

        public Criteria andChannelDishonorTraceNoGreaterThanOrEqualTo(String value) {
            addCriterion("channel_dishonor_trace_no >=", value, "channelDishonorTraceNo");
            return (Criteria) this;
        }

        public Criteria andChannelDishonorTraceNoLessThan(String value) {
            addCriterion("channel_dishonor_trace_no <", value, "channelDishonorTraceNo");
            return (Criteria) this;
        }

        public Criteria andChannelDishonorTraceNoLessThanOrEqualTo(String value) {
            addCriterion("channel_dishonor_trace_no <=", value, "channelDishonorTraceNo");
            return (Criteria) this;
        }

        public Criteria andChannelDishonorTraceNoLike(String value) {
            addCriterion("channel_dishonor_trace_no like", value, "channelDishonorTraceNo");
            return (Criteria) this;
        }

        public Criteria andChannelDishonorTraceNoNotLike(String value) {
            addCriterion("channel_dishonor_trace_no not like", value, "channelDishonorTraceNo");
            return (Criteria) this;
        }

        public Criteria andChannelDishonorTraceNoIn(List<String> values) {
            addCriterion("channel_dishonor_trace_no in", values, "channelDishonorTraceNo");
            return (Criteria) this;
        }

        public Criteria andChannelDishonorTraceNoNotIn(List<String> values) {
            addCriterion("channel_dishonor_trace_no not in", values, "channelDishonorTraceNo");
            return (Criteria) this;
        }

        public Criteria andChannelDishonorTraceNoBetween(String value1, String value2) {
            addCriterion("channel_dishonor_trace_no between", value1, value2, "channelDishonorTraceNo");
            return (Criteria) this;
        }

        public Criteria andChannelDishonorTraceNoNotBetween(String value1, String value2) {
            addCriterion("channel_dishonor_trace_no not between", value1, value2, "channelDishonorTraceNo");
            return (Criteria) this;
        }

        public Criteria andChannelErrorCodeIsNull() {
            addCriterion("channel_error_code is null");
            return (Criteria) this;
        }

        public Criteria andChannelErrorCodeIsNotNull() {
            addCriterion("channel_error_code is not null");
            return (Criteria) this;
        }

        public Criteria andChannelErrorCodeEqualTo(String value) {
            addCriterion("channel_error_code =", value, "channelErrorCode");
            return (Criteria) this;
        }

        public Criteria andChannelErrorCodeNotEqualTo(String value) {
            addCriterion("channel_error_code <>", value, "channelErrorCode");
            return (Criteria) this;
        }

        public Criteria andChannelErrorCodeGreaterThan(String value) {
            addCriterion("channel_error_code >", value, "channelErrorCode");
            return (Criteria) this;
        }

        public Criteria andChannelErrorCodeGreaterThanOrEqualTo(String value) {
            addCriterion("channel_error_code >=", value, "channelErrorCode");
            return (Criteria) this;
        }

        public Criteria andChannelErrorCodeLessThan(String value) {
            addCriterion("channel_error_code <", value, "channelErrorCode");
            return (Criteria) this;
        }

        public Criteria andChannelErrorCodeLessThanOrEqualTo(String value) {
            addCriterion("channel_error_code <=", value, "channelErrorCode");
            return (Criteria) this;
        }

        public Criteria andChannelErrorCodeLike(String value) {
            addCriterion("channel_error_code like", value, "channelErrorCode");
            return (Criteria) this;
        }

        public Criteria andChannelErrorCodeNotLike(String value) {
            addCriterion("channel_error_code not like", value, "channelErrorCode");
            return (Criteria) this;
        }

        public Criteria andChannelErrorCodeIn(List<String> values) {
            addCriterion("channel_error_code in", values, "channelErrorCode");
            return (Criteria) this;
        }

        public Criteria andChannelErrorCodeNotIn(List<String> values) {
            addCriterion("channel_error_code not in", values, "channelErrorCode");
            return (Criteria) this;
        }

        public Criteria andChannelErrorCodeBetween(String value1, String value2) {
            addCriterion("channel_error_code between", value1, value2, "channelErrorCode");
            return (Criteria) this;
        }

        public Criteria andChannelErrorCodeNotBetween(String value1, String value2) {
            addCriterion("channel_error_code not between", value1, value2, "channelErrorCode");
            return (Criteria) this;
        }

        public Criteria andBusinessEntityIsNull() {
            addCriterion("business_entity is null");
            return (Criteria) this;
        }

        public Criteria andBusinessEntityIsNotNull() {
            addCriterion("business_entity is not null");
            return (Criteria) this;
        }

        public Criteria andBusinessEntityEqualTo(String value) {
            addCriterion("business_entity =", value, "businessEntity");
            return (Criteria) this;
        }

        public Criteria andBusinessEntityNotEqualTo(String value) {
            addCriterion("business_entity <>", value, "businessEntity");
            return (Criteria) this;
        }

        public Criteria andBusinessEntityGreaterThan(String value) {
            addCriterion("business_entity >", value, "businessEntity");
            return (Criteria) this;
        }

        public Criteria andBusinessEntityGreaterThanOrEqualTo(String value) {
            addCriterion("business_entity >=", value, "businessEntity");
            return (Criteria) this;
        }

        public Criteria andBusinessEntityLessThan(String value) {
            addCriterion("business_entity <", value, "businessEntity");
            return (Criteria) this;
        }

        public Criteria andBusinessEntityLessThanOrEqualTo(String value) {
            addCriterion("business_entity <=", value, "businessEntity");
            return (Criteria) this;
        }

        public Criteria andBusinessEntityLike(String value) {
            addCriterion("business_entity like", value, "businessEntity");
            return (Criteria) this;
        }

        public Criteria andBusinessEntityNotLike(String value) {
            addCriterion("business_entity not like", value, "businessEntity");
            return (Criteria) this;
        }

        public Criteria andBusinessEntityIn(List<String> values) {
            addCriterion("business_entity in", values, "businessEntity");
            return (Criteria) this;
        }

        public Criteria andBusinessEntityNotIn(List<String> values) {
            addCriterion("business_entity not in", values, "businessEntity");
            return (Criteria) this;
        }

        public Criteria andBusinessEntityBetween(String value1, String value2) {
            addCriterion("business_entity between", value1, value2, "businessEntity");
            return (Criteria) this;
        }

        public Criteria andBusinessEntityNotBetween(String value1, String value2) {
            addCriterion("business_entity not between", value1, value2, "businessEntity");
            return (Criteria) this;
        }

        public Criteria andNotifyUriIsNull() {
            addCriterion("notify_uri is null");
            return (Criteria) this;
        }

        public Criteria andNotifyUriIsNotNull() {
            addCriterion("notify_uri is not null");
            return (Criteria) this;
        }

        public Criteria andNotifyUriEqualTo(String value) {
            addCriterion("notify_uri =", value, "notifyUri");
            return (Criteria) this;
        }

        public Criteria andNotifyUriNotEqualTo(String value) {
            addCriterion("notify_uri <>", value, "notifyUri");
            return (Criteria) this;
        }

        public Criteria andNotifyUriGreaterThan(String value) {
            addCriterion("notify_uri >", value, "notifyUri");
            return (Criteria) this;
        }

        public Criteria andNotifyUriGreaterThanOrEqualTo(String value) {
            addCriterion("notify_uri >=", value, "notifyUri");
            return (Criteria) this;
        }

        public Criteria andNotifyUriLessThan(String value) {
            addCriterion("notify_uri <", value, "notifyUri");
            return (Criteria) this;
        }

        public Criteria andNotifyUriLessThanOrEqualTo(String value) {
            addCriterion("notify_uri <=", value, "notifyUri");
            return (Criteria) this;
        }

        public Criteria andNotifyUriLike(String value) {
            addCriterion("notify_uri like", value, "notifyUri");
            return (Criteria) this;
        }

        public Criteria andNotifyUriNotLike(String value) {
            addCriterion("notify_uri not like", value, "notifyUri");
            return (Criteria) this;
        }

        public Criteria andNotifyUriIn(List<String> values) {
            addCriterion("notify_uri in", values, "notifyUri");
            return (Criteria) this;
        }

        public Criteria andNotifyUriNotIn(List<String> values) {
            addCriterion("notify_uri not in", values, "notifyUri");
            return (Criteria) this;
        }

        public Criteria andNotifyUriBetween(String value1, String value2) {
            addCriterion("notify_uri between", value1, value2, "notifyUri");
            return (Criteria) this;
        }

        public Criteria andNotifyUriNotBetween(String value1, String value2) {
            addCriterion("notify_uri not between", value1, value2, "notifyUri");
            return (Criteria) this;
        }

        public Criteria andExtendInfoIsNull() {
            addCriterion("extend_info is null");
            return (Criteria) this;
        }

        public Criteria andExtendInfoIsNotNull() {
            addCriterion("extend_info is not null");
            return (Criteria) this;
        }

        public Criteria andExtendInfoEqualTo(String value) {
            addCriterion("extend_info =", value, "extendInfo");
            return (Criteria) this;
        }

        public Criteria andExtendInfoNotEqualTo(String value) {
            addCriterion("extend_info <>", value, "extendInfo");
            return (Criteria) this;
        }

        public Criteria andExtendInfoGreaterThan(String value) {
            addCriterion("extend_info >", value, "extendInfo");
            return (Criteria) this;
        }

        public Criteria andExtendInfoGreaterThanOrEqualTo(String value) {
            addCriterion("extend_info >=", value, "extendInfo");
            return (Criteria) this;
        }

        public Criteria andExtendInfoLessThan(String value) {
            addCriterion("extend_info <", value, "extendInfo");
            return (Criteria) this;
        }

        public Criteria andExtendInfoLessThanOrEqualTo(String value) {
            addCriterion("extend_info <=", value, "extendInfo");
            return (Criteria) this;
        }

        public Criteria andExtendInfoLike(String value) {
            addCriterion("extend_info like", value, "extendInfo");
            return (Criteria) this;
        }

        public Criteria andExtendInfoNotLike(String value) {
            addCriterion("extend_info not like", value, "extendInfo");
            return (Criteria) this;
        }

        public Criteria andExtendInfoIn(List<String> values) {
            addCriterion("extend_info in", values, "extendInfo");
            return (Criteria) this;
        }

        public Criteria andExtendInfoNotIn(List<String> values) {
            addCriterion("extend_info not in", values, "extendInfo");
            return (Criteria) this;
        }

        public Criteria andExtendInfoBetween(String value1, String value2) {
            addCriterion("extend_info between", value1, value2, "extendInfo");
            return (Criteria) this;
        }

        public Criteria andExtendInfoNotBetween(String value1, String value2) {
            addCriterion("extend_info not between", value1, value2, "extendInfo");
            return (Criteria) this;
        }

        public Criteria andBizInfoIsNull() {
            addCriterion("biz_info is null");
            return (Criteria) this;
        }

        public Criteria andBizInfoIsNotNull() {
            addCriterion("biz_info is not null");
            return (Criteria) this;
        }

        public Criteria andBizInfoEqualTo(String value) {
            addCriterion("biz_info =", value, "bizInfo");
            return (Criteria) this;
        }

        public Criteria andBizInfoNotEqualTo(String value) {
            addCriterion("biz_info <>", value, "bizInfo");
            return (Criteria) this;
        }

        public Criteria andBizInfoGreaterThan(String value) {
            addCriterion("biz_info >", value, "bizInfo");
            return (Criteria) this;
        }

        public Criteria andBizInfoGreaterThanOrEqualTo(String value) {
            addCriterion("biz_info >=", value, "bizInfo");
            return (Criteria) this;
        }

        public Criteria andBizInfoLessThan(String value) {
            addCriterion("biz_info <", value, "bizInfo");
            return (Criteria) this;
        }

        public Criteria andBizInfoLessThanOrEqualTo(String value) {
            addCriterion("biz_info <=", value, "bizInfo");
            return (Criteria) this;
        }

        public Criteria andBizInfoLike(String value) {
            addCriterion("biz_info like", value, "bizInfo");
            return (Criteria) this;
        }

        public Criteria andBizInfoNotLike(String value) {
            addCriterion("biz_info not like", value, "bizInfo");
            return (Criteria) this;
        }

        public Criteria andBizInfoIn(List<String> values) {
            addCriterion("biz_info in", values, "bizInfo");
            return (Criteria) this;
        }

        public Criteria andBizInfoNotIn(List<String> values) {
            addCriterion("biz_info not in", values, "bizInfo");
            return (Criteria) this;
        }

        public Criteria andBizInfoBetween(String value1, String value2) {
            addCriterion("biz_info between", value1, value2, "bizInfo");
            return (Criteria) this;
        }

        public Criteria andBizInfoNotBetween(String value1, String value2) {
            addCriterion("biz_info not between", value1, value2, "bizInfo");
            return (Criteria) this;
        }

        public Criteria andEnvIsNull() {
            addCriterion("env is null");
            return (Criteria) this;
        }

        public Criteria andEnvIsNotNull() {
            addCriterion("env is not null");
            return (Criteria) this;
        }

        public Criteria andEnvEqualTo(Integer value) {
            addCriterion("env =", value, "env");
            return (Criteria) this;
        }

        public Criteria andEnvNotEqualTo(Integer value) {
            addCriterion("env <>", value, "env");
            return (Criteria) this;
        }

        public Criteria andEnvGreaterThan(Integer value) {
            addCriterion("env >", value, "env");
            return (Criteria) this;
        }

        public Criteria andEnvGreaterThanOrEqualTo(Integer value) {
            addCriterion("env >=", value, "env");
            return (Criteria) this;
        }

        public Criteria andEnvLessThan(Integer value) {
            addCriterion("env <", value, "env");
            return (Criteria) this;
        }

        public Criteria andEnvLessThanOrEqualTo(Integer value) {
            addCriterion("env <=", value, "env");
            return (Criteria) this;
        }

        public Criteria andEnvIn(List<Integer> values) {
            addCriterion("env in", values, "env");
            return (Criteria) this;
        }

        public Criteria andEnvNotIn(List<Integer> values) {
            addCriterion("env not in", values, "env");
            return (Criteria) this;
        }

        public Criteria andEnvBetween(Integer value1, Integer value2) {
            addCriterion("env between", value1, value2, "env");
            return (Criteria) this;
        }

        public Criteria andEnvNotBetween(Integer value1, Integer value2) {
            addCriterion("env not between", value1, value2, "env");
            return (Criteria) this;
        }
    }

    /**
     * This class was generated by MyBatis Generator.
     * This class corresponds to the database table tb_trans_pay_order
     *
     * @mbg.generated do_not_delete_during_merge Wed Jan 26 17:49:11 CST 2022
     */
    public static class Criteria extends GeneratedCriteria {

        protected Criteria() {
            super();
        }
    }

    /**
     * This class was generated by MyBatis Generator.
     * This class corresponds to the database table tb_trans_pay_order
     *
     * @mbg.generated Wed Jan 26 17:49:11 CST 2022
     */
    public static class Criterion {

        private String condition;

        private Object value;

        private Object secondValue;

        private boolean noValue;

        private boolean singleValue;

        private boolean betweenValue;

        private boolean listValue;

        private String typeHandler;

        protected Criterion(String condition) {
            super();
            this.condition = condition;
            this.typeHandler = null;
            this.noValue = true;
        }

        protected Criterion(String condition, Object value, String typeHandler) {
            super();
            this.condition = condition;
            this.value = value;
            this.typeHandler = typeHandler;
            if (value instanceof List<?>) {
                this.listValue = true;
            } else {
                this.singleValue = true;
            }
        }

        protected Criterion(String condition, Object value) {
            this(condition, value, null);
        }

        protected Criterion(String condition, Object value, Object secondValue, String typeHandler) {
            super();
            this.condition = condition;
            this.value = value;
            this.secondValue = secondValue;
            this.typeHandler = typeHandler;
            this.betweenValue = true;
        }

        protected Criterion(String condition, Object value, Object secondValue) {
            this(condition, value, secondValue, null);
        }

        public String getCondition() {
            return condition;
        }

        public Object getValue() {
            return value;
        }

        public Object getSecondValue() {
            return secondValue;
        }

        public boolean isNoValue() {
            return noValue;
        }

        public boolean isSingleValue() {
            return singleValue;
        }

        public boolean isBetweenValue() {
            return betweenValue;
        }

        public boolean isListValue() {
            return listValue;
        }

        public String getTypeHandler() {
            return typeHandler;
        }
    }
}