package com.magicliang.transaction.sys.common.dal.mybatis.po;

import java.util.Date;

/**
 * This class was generated by MyBatis Generator.
 * This class corresponds to the database table tb_trans_pay_order
 */
public class TransPayOrderPo {

    /**
     * Database Column Remarks:
     * 自增物理主键，单表唯一
     * <p>
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column tb_trans_pay_order.id
     *
     * @mbg.generated Wed Jan 26 17:49:11 CST 2022
     */
    private Long id;

    /**
     * Database Column Remarks:
     * 创建时间
     * <p>
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column tb_trans_pay_order.gmt_created
     *
     * @mbg.generated Wed Jan 26 17:49:11 CST 2022
     */
    private Date gmtCreated;

    /**
     * Database Column Remarks:
     * 最后修改时间
     * <p>
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column tb_trans_pay_order.gmt_modified
     *
     * @mbg.generated Wed Jan 26 17:49:11 CST 2022
     */
    private Date gmtModified;

    /**
     * Database Column Remarks:
     * 支付订单号，业务主键，全局唯一
     * <p>
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column tb_trans_pay_order.pay_order_no
     *
     * @mbg.generated Wed Jan 26 17:49:11 CST 2022
     */
    private Long payOrderNo;

    /**
     * Database Column Remarks:
     * 支付订单来源系统
     * <p>
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column tb_trans_pay_order.sys_code
     *
     * @mbg.generated Wed Jan 26 17:49:11 CST 2022
     */
    private String sysCode;

    /**
     * Database Column Remarks:
     * 业务标识码
     * <p>
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column tb_trans_pay_order.biz_identify_no
     *
     * @mbg.generated Wed Jan 26 17:49:11 CST 2022
     */
    private String bizIdentifyNo;

    /**
     * Database Column Remarks:
     * 上游业务号，语义同 out_biz_no，与业务标识码联合后，必须全局唯一，可以作为分表键
     * <p>
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column tb_trans_pay_order.biz_unique_no
     *
     * @mbg.generated Wed Jan 26 17:49:11 CST 2022
     */
    private String bizUniqueNo;

    /**
     * Database Column Remarks:
     * 支付单金额，单位为分，全为正数
     * <p>
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column tb_trans_pay_order.money
     *
     * @mbg.generated Wed Jan 26 17:49:11 CST 2022
     */
    private Long money;

    /**
     * Database Column Remarks:
     * 支付通道类型，1 支付宝 2 微信支付
     * <p>
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column tb_trans_pay_order.pay_channel_type
     *
     * @mbg.generated Wed Jan 26 17:49:11 CST 2022
     */
    private Integer payChannelType;

    /**
     * Database Column Remarks:
     * 目标账户类型，1 银行卡 2 账户余额
     * <p>
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column tb_trans_pay_order.target_account_type
     *
     * @mbg.generated Wed Jan 26 17:49:11 CST 2022
     */
    private Integer targetAccountType;

    /**
     * Database Column Remarks:
     * 会计账目条目 1 借 debit 2 贷 credit
     * <p>
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column tb_trans_pay_order.accounting_entry
     *
     * @mbg.generated Wed Jan 26 17:49:11 CST 2022
     */
    private Integer accountingEntry;

    /**
     * Database Column Remarks:
     * 受理时间
     * <p>
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column tb_trans_pay_order.gmt_accepted_time
     *
     * @mbg.generated Wed Jan 26 17:49:11 CST 2022
     */
    private Date gmtAcceptedTime;

    /**
     * Database Column Remarks:
     * 支付时间
     * <p>
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column tb_trans_pay_order.gmt_payment_begin_time
     *
     * @mbg.generated Wed Jan 26 17:49:11 CST 2022
     */
    private Date gmtPaymentBeginTime;

    /**
     * Database Column Remarks:
     * 支付成功时间
     * <p>
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column tb_trans_pay_order.gmt_payment_success_time
     *
     * @mbg.generated Wed Jan 26 17:49:11 CST 2022
     */
    private Date gmtPaymentSuccessTime;

    /**
     * Database Column Remarks:
     * 支付失败时间
     * <p>
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column tb_trans_pay_order.gmt_payment_failure_time
     *
     * @mbg.generated Wed Jan 26 17:49:11 CST 2022
     */
    private Date gmtPaymentFailureTime;

    /**
     * Database Column Remarks:
     * 支付关闭时间
     * <p>
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column tb_trans_pay_order.gmt_payment_closed_time
     *
     * @mbg.generated Wed Jan 26 17:49:11 CST 2022
     */
    private Date gmtPaymentClosedTime;

    /**
     * Database Column Remarks:
     * 支付退票时间
     * <p>
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column tb_trans_pay_order.gmt_payment_bounced_time
     *
     * @mbg.generated Wed Jan 26 17:49:11 CST 2022
     */
    private Date gmtPaymentBouncedTime;

    /**
     * Database Column Remarks:
     * 支付状态，1 初始化 2 支付中 3 支付成功 4 支付失败 5 关闭 6 支付退票
     * <p>
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column tb_trans_pay_order.status
     *
     * @mbg.generated Wed Jan 26 17:49:11 CST 2022
     */
    private Integer status;

    /**
     * Database Column Remarks:
     * 版本
     * <p>
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column tb_trans_pay_order.version
     *
     * @mbg.generated Wed Jan 26 17:49:11 CST 2022
     */
    private Integer version;

    /**
     * Database Column Remarks:
     * 支付备注
     * <p>
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column tb_trans_pay_order.memo
     *
     * @mbg.generated Wed Jan 26 17:49:11 CST 2022
     */
    private String memo;

    /**
     * Database Column Remarks:
     * 支付通道的支付流水号，单一通道必须全局唯一
     * <p>
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column tb_trans_pay_order.channel_payment_trace_no
     *
     * @mbg.generated Wed Jan 26 17:49:11 CST 2022
     */
    private String channelPaymentTraceNo;

    /**
     * Database Column Remarks:
     * 支付通道的退票流水号，单一通道必须全局唯一
     * <p>
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column tb_trans_pay_order.channel_dishonor_trace_no
     *
     * @mbg.generated Wed Jan 26 17:49:11 CST 2022
     */
    private String channelDishonorTraceNo;

    /**
     * Database Column Remarks:
     * 支付错误码
     * <p>
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column tb_trans_pay_order.channel_error_code
     *
     * @mbg.generated Wed Jan 26 17:49:11 CST 2022
     */
    private String channelErrorCode;

    /**
     * Database Column Remarks:
     * 支付主体，上游系统选填
     * <p>
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column tb_trans_pay_order.business_entity
     *
     * @mbg.generated Wed Jan 26 17:49:11 CST 2022
     */
    private String businessEntity;

    /**
     * Database Column Remarks:
     * 通知地址
     * <p>
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column tb_trans_pay_order.notify_uri
     *
     * @mbg.generated Wed Jan 26 17:49:11 CST 2022
     */
    private String notifyUri;

    /**
     * Database Column Remarks:
     * 扩展信息，平台能力抽象，用于日后本服务特定的平台能力和流程打标用，不透传到链路的其他系统中，必须是 json 格式
     * <p>
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column tb_trans_pay_order.extend_info
     *
     * @mbg.generated Wed Jan 26 17:49:11 CST 2022
     */
    private String extendInfo;

    /**
     * Database Column Remarks:
     * 扩展信息，业务能力抽象，透传到链路的其他系统中，本系统不理解，必须是 json 格式
     * <p>
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column tb_trans_pay_order.biz_info
     *
     * @mbg.generated Wed Jan 26 17:49:11 CST 2022
     */
    private String bizInfo;

    /**
     * Database Column Remarks:
     * 环境，1 dev 2 test 3 staging 4 prod
     * <p>
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column tb_trans_pay_order.env
     *
     * @mbg.generated Wed Jan 26 17:49:11 CST 2022
     */
    private Integer env;

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column tb_trans_pay_order.id
     *
     * @return the value of tb_trans_pay_order.id
     * @mbg.generated Wed Jan 26 17:49:11 CST 2022
     */
    public Long getId() {
        return id;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column tb_trans_pay_order.id
     *
     * @param id the value for tb_trans_pay_order.id
     * @mbg.generated Wed Jan 26 17:49:11 CST 2022
     */
    public void setId(Long id) {
        this.id = id;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column tb_trans_pay_order.gmt_created
     *
     * @return the value of tb_trans_pay_order.gmt_created
     * @mbg.generated Wed Jan 26 17:49:11 CST 2022
     */
    public Date getGmtCreated() {
        return gmtCreated;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column tb_trans_pay_order.gmt_created
     *
     * @param gmtCreated the value for tb_trans_pay_order.gmt_created
     * @mbg.generated Wed Jan 26 17:49:11 CST 2022
     */
    public void setGmtCreated(Date gmtCreated) {
        this.gmtCreated = gmtCreated;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column tb_trans_pay_order.gmt_modified
     *
     * @return the value of tb_trans_pay_order.gmt_modified
     * @mbg.generated Wed Jan 26 17:49:11 CST 2022
     */
    public Date getGmtModified() {
        return gmtModified;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column tb_trans_pay_order.gmt_modified
     *
     * @param gmtModified the value for tb_trans_pay_order.gmt_modified
     * @mbg.generated Wed Jan 26 17:49:11 CST 2022
     */
    public void setGmtModified(Date gmtModified) {
        this.gmtModified = gmtModified;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column tb_trans_pay_order.pay_order_no
     *
     * @return the value of tb_trans_pay_order.pay_order_no
     * @mbg.generated Wed Jan 26 17:49:11 CST 2022
     */
    public Long getPayOrderNo() {
        return payOrderNo;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column tb_trans_pay_order.pay_order_no
     *
     * @param payOrderNo the value for tb_trans_pay_order.pay_order_no
     * @mbg.generated Wed Jan 26 17:49:11 CST 2022
     */
    public void setPayOrderNo(Long payOrderNo) {
        this.payOrderNo = payOrderNo;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column tb_trans_pay_order.sys_code
     *
     * @return the value of tb_trans_pay_order.sys_code
     * @mbg.generated Wed Jan 26 17:49:11 CST 2022
     */
    public String getSysCode() {
        return sysCode;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column tb_trans_pay_order.sys_code
     *
     * @param sysCode the value for tb_trans_pay_order.sys_code
     * @mbg.generated Wed Jan 26 17:49:11 CST 2022
     */
    public void setSysCode(String sysCode) {
        this.sysCode = sysCode == null ? null : sysCode.trim();
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column tb_trans_pay_order.biz_identify_no
     *
     * @return the value of tb_trans_pay_order.biz_identify_no
     * @mbg.generated Wed Jan 26 17:49:11 CST 2022
     */
    public String getBizIdentifyNo() {
        return bizIdentifyNo;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column tb_trans_pay_order.biz_identify_no
     *
     * @param bizIdentifyNo the value for tb_trans_pay_order.biz_identify_no
     * @mbg.generated Wed Jan 26 17:49:11 CST 2022
     */
    public void setBizIdentifyNo(String bizIdentifyNo) {
        this.bizIdentifyNo = bizIdentifyNo == null ? null : bizIdentifyNo.trim();
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column tb_trans_pay_order.biz_unique_no
     *
     * @return the value of tb_trans_pay_order.biz_unique_no
     * @mbg.generated Wed Jan 26 17:49:11 CST 2022
     */
    public String getBizUniqueNo() {
        return bizUniqueNo;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column tb_trans_pay_order.biz_unique_no
     *
     * @param bizUniqueNo the value for tb_trans_pay_order.biz_unique_no
     * @mbg.generated Wed Jan 26 17:49:11 CST 2022
     */
    public void setBizUniqueNo(String bizUniqueNo) {
        this.bizUniqueNo = bizUniqueNo == null ? null : bizUniqueNo.trim();
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column tb_trans_pay_order.money
     *
     * @return the value of tb_trans_pay_order.money
     * @mbg.generated Wed Jan 26 17:49:11 CST 2022
     */
    public Long getMoney() {
        return money;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column tb_trans_pay_order.money
     *
     * @param money the value for tb_trans_pay_order.money
     * @mbg.generated Wed Jan 26 17:49:11 CST 2022
     */
    public void setMoney(Long money) {
        this.money = money;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column tb_trans_pay_order.pay_channel_type
     *
     * @return the value of tb_trans_pay_order.pay_channel_type
     * @mbg.generated Wed Jan 26 17:49:11 CST 2022
     */
    public Integer getPayChannelType() {
        return payChannelType;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column tb_trans_pay_order.pay_channel_type
     *
     * @param payChannelType the value for tb_trans_pay_order.pay_channel_type
     * @mbg.generated Wed Jan 26 17:49:11 CST 2022
     */
    public void setPayChannelType(Integer payChannelType) {
        this.payChannelType = payChannelType;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column tb_trans_pay_order.target_account_type
     *
     * @return the value of tb_trans_pay_order.target_account_type
     * @mbg.generated Wed Jan 26 17:49:11 CST 2022
     */
    public Integer getTargetAccountType() {
        return targetAccountType;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column tb_trans_pay_order.target_account_type
     *
     * @param targetAccountType the value for tb_trans_pay_order.target_account_type
     * @mbg.generated Wed Jan 26 17:49:11 CST 2022
     */
    public void setTargetAccountType(Integer targetAccountType) {
        this.targetAccountType = targetAccountType;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column tb_trans_pay_order.accounting_entry
     *
     * @return the value of tb_trans_pay_order.accounting_entry
     * @mbg.generated Wed Jan 26 17:49:11 CST 2022
     */
    public Integer getAccountingEntry() {
        return accountingEntry;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column tb_trans_pay_order.accounting_entry
     *
     * @param accountingEntry the value for tb_trans_pay_order.accounting_entry
     * @mbg.generated Wed Jan 26 17:49:11 CST 2022
     */
    public void setAccountingEntry(Integer accountingEntry) {
        this.accountingEntry = accountingEntry;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column tb_trans_pay_order.gmt_accepted_time
     *
     * @return the value of tb_trans_pay_order.gmt_accepted_time
     * @mbg.generated Wed Jan 26 17:49:11 CST 2022
     */
    public Date getGmtAcceptedTime() {
        return gmtAcceptedTime;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column tb_trans_pay_order.gmt_accepted_time
     *
     * @param gmtAcceptedTime the value for tb_trans_pay_order.gmt_accepted_time
     * @mbg.generated Wed Jan 26 17:49:11 CST 2022
     */
    public void setGmtAcceptedTime(Date gmtAcceptedTime) {
        this.gmtAcceptedTime = gmtAcceptedTime;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column tb_trans_pay_order.gmt_payment_begin_time
     *
     * @return the value of tb_trans_pay_order.gmt_payment_begin_time
     * @mbg.generated Wed Jan 26 17:49:11 CST 2022
     */
    public Date getGmtPaymentBeginTime() {
        return gmtPaymentBeginTime;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column tb_trans_pay_order.gmt_payment_begin_time
     *
     * @param gmtPaymentBeginTime the value for tb_trans_pay_order.gmt_payment_begin_time
     * @mbg.generated Wed Jan 26 17:49:11 CST 2022
     */
    public void setGmtPaymentBeginTime(Date gmtPaymentBeginTime) {
        this.gmtPaymentBeginTime = gmtPaymentBeginTime;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column tb_trans_pay_order.gmt_payment_success_time
     *
     * @return the value of tb_trans_pay_order.gmt_payment_success_time
     * @mbg.generated Wed Jan 26 17:49:11 CST 2022
     */
    public Date getGmtPaymentSuccessTime() {
        return gmtPaymentSuccessTime;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column tb_trans_pay_order.gmt_payment_success_time
     *
     * @param gmtPaymentSuccessTime the value for tb_trans_pay_order.gmt_payment_success_time
     * @mbg.generated Wed Jan 26 17:49:11 CST 2022
     */
    public void setGmtPaymentSuccessTime(Date gmtPaymentSuccessTime) {
        this.gmtPaymentSuccessTime = gmtPaymentSuccessTime;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column tb_trans_pay_order.gmt_payment_failure_time
     *
     * @return the value of tb_trans_pay_order.gmt_payment_failure_time
     * @mbg.generated Wed Jan 26 17:49:11 CST 2022
     */
    public Date getGmtPaymentFailureTime() {
        return gmtPaymentFailureTime;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column tb_trans_pay_order.gmt_payment_failure_time
     *
     * @param gmtPaymentFailureTime the value for tb_trans_pay_order.gmt_payment_failure_time
     * @mbg.generated Wed Jan 26 17:49:11 CST 2022
     */
    public void setGmtPaymentFailureTime(Date gmtPaymentFailureTime) {
        this.gmtPaymentFailureTime = gmtPaymentFailureTime;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column tb_trans_pay_order.gmt_payment_closed_time
     *
     * @return the value of tb_trans_pay_order.gmt_payment_closed_time
     * @mbg.generated Wed Jan 26 17:49:11 CST 2022
     */
    public Date getGmtPaymentClosedTime() {
        return gmtPaymentClosedTime;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column tb_trans_pay_order.gmt_payment_closed_time
     *
     * @param gmtPaymentClosedTime the value for tb_trans_pay_order.gmt_payment_closed_time
     * @mbg.generated Wed Jan 26 17:49:11 CST 2022
     */
    public void setGmtPaymentClosedTime(Date gmtPaymentClosedTime) {
        this.gmtPaymentClosedTime = gmtPaymentClosedTime;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column tb_trans_pay_order.gmt_payment_bounced_time
     *
     * @return the value of tb_trans_pay_order.gmt_payment_bounced_time
     * @mbg.generated Wed Jan 26 17:49:11 CST 2022
     */
    public Date getGmtPaymentBouncedTime() {
        return gmtPaymentBouncedTime;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column tb_trans_pay_order.gmt_payment_bounced_time
     *
     * @param gmtPaymentBouncedTime the value for tb_trans_pay_order.gmt_payment_bounced_time
     * @mbg.generated Wed Jan 26 17:49:11 CST 2022
     */
    public void setGmtPaymentBouncedTime(Date gmtPaymentBouncedTime) {
        this.gmtPaymentBouncedTime = gmtPaymentBouncedTime;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column tb_trans_pay_order.status
     *
     * @return the value of tb_trans_pay_order.status
     * @mbg.generated Wed Jan 26 17:49:11 CST 2022
     */
    public Integer getStatus() {
        return status;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column tb_trans_pay_order.status
     *
     * @param status the value for tb_trans_pay_order.status
     * @mbg.generated Wed Jan 26 17:49:11 CST 2022
     */
    public void setStatus(Integer status) {
        this.status = status;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column tb_trans_pay_order.version
     *
     * @return the value of tb_trans_pay_order.version
     * @mbg.generated Wed Jan 26 17:49:11 CST 2022
     */
    public Integer getVersion() {
        return version;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column tb_trans_pay_order.version
     *
     * @param version the value for tb_trans_pay_order.version
     * @mbg.generated Wed Jan 26 17:49:11 CST 2022
     */
    public void setVersion(Integer version) {
        this.version = version;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column tb_trans_pay_order.memo
     *
     * @return the value of tb_trans_pay_order.memo
     * @mbg.generated Wed Jan 26 17:49:11 CST 2022
     */
    public String getMemo() {
        return memo;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column tb_trans_pay_order.memo
     *
     * @param memo the value for tb_trans_pay_order.memo
     * @mbg.generated Wed Jan 26 17:49:11 CST 2022
     */
    public void setMemo(String memo) {
        this.memo = memo == null ? null : memo.trim();
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column tb_trans_pay_order.channel_payment_trace_no
     *
     * @return the value of tb_trans_pay_order.channel_payment_trace_no
     * @mbg.generated Wed Jan 26 17:49:11 CST 2022
     */
    public String getChannelPaymentTraceNo() {
        return channelPaymentTraceNo;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column tb_trans_pay_order.channel_payment_trace_no
     *
     * @param channelPaymentTraceNo the value for tb_trans_pay_order.channel_payment_trace_no
     * @mbg.generated Wed Jan 26 17:49:11 CST 2022
     */
    public void setChannelPaymentTraceNo(String channelPaymentTraceNo) {
        this.channelPaymentTraceNo = channelPaymentTraceNo == null ? null : channelPaymentTraceNo.trim();
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column tb_trans_pay_order.channel_dishonor_trace_no
     *
     * @return the value of tb_trans_pay_order.channel_dishonor_trace_no
     * @mbg.generated Wed Jan 26 17:49:11 CST 2022
     */
    public String getChannelDishonorTraceNo() {
        return channelDishonorTraceNo;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column tb_trans_pay_order.channel_dishonor_trace_no
     *
     * @param channelDishonorTraceNo the value for tb_trans_pay_order.channel_dishonor_trace_no
     * @mbg.generated Wed Jan 26 17:49:11 CST 2022
     */
    public void setChannelDishonorTraceNo(String channelDishonorTraceNo) {
        this.channelDishonorTraceNo = channelDishonorTraceNo == null ? null : channelDishonorTraceNo.trim();
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column tb_trans_pay_order.channel_error_code
     *
     * @return the value of tb_trans_pay_order.channel_error_code
     * @mbg.generated Wed Jan 26 17:49:11 CST 2022
     */
    public String getChannelErrorCode() {
        return channelErrorCode;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column tb_trans_pay_order.channel_error_code
     *
     * @param channelErrorCode the value for tb_trans_pay_order.channel_error_code
     * @mbg.generated Wed Jan 26 17:49:11 CST 2022
     */
    public void setChannelErrorCode(String channelErrorCode) {
        this.channelErrorCode = channelErrorCode == null ? null : channelErrorCode.trim();
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column tb_trans_pay_order.business_entity
     *
     * @return the value of tb_trans_pay_order.business_entity
     * @mbg.generated Wed Jan 26 17:49:11 CST 2022
     */
    public String getBusinessEntity() {
        return businessEntity;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column tb_trans_pay_order.business_entity
     *
     * @param businessEntity the value for tb_trans_pay_order.business_entity
     * @mbg.generated Wed Jan 26 17:49:11 CST 2022
     */
    public void setBusinessEntity(String businessEntity) {
        this.businessEntity = businessEntity == null ? null : businessEntity.trim();
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column tb_trans_pay_order.notify_uri
     *
     * @return the value of tb_trans_pay_order.notify_uri
     * @mbg.generated Wed Jan 26 17:49:11 CST 2022
     */
    public String getNotifyUri() {
        return notifyUri;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column tb_trans_pay_order.notify_uri
     *
     * @param notifyUri the value for tb_trans_pay_order.notify_uri
     * @mbg.generated Wed Jan 26 17:49:11 CST 2022
     */
    public void setNotifyUri(String notifyUri) {
        this.notifyUri = notifyUri == null ? null : notifyUri.trim();
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column tb_trans_pay_order.extend_info
     *
     * @return the value of tb_trans_pay_order.extend_info
     * @mbg.generated Wed Jan 26 17:49:11 CST 2022
     */
    public String getExtendInfo() {
        return extendInfo;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column tb_trans_pay_order.extend_info
     *
     * @param extendInfo the value for tb_trans_pay_order.extend_info
     * @mbg.generated Wed Jan 26 17:49:11 CST 2022
     */
    public void setExtendInfo(String extendInfo) {
        this.extendInfo = extendInfo == null ? null : extendInfo.trim();
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column tb_trans_pay_order.biz_info
     *
     * @return the value of tb_trans_pay_order.biz_info
     * @mbg.generated Wed Jan 26 17:49:11 CST 2022
     */
    public String getBizInfo() {
        return bizInfo;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column tb_trans_pay_order.biz_info
     *
     * @param bizInfo the value for tb_trans_pay_order.biz_info
     * @mbg.generated Wed Jan 26 17:49:11 CST 2022
     */
    public void setBizInfo(String bizInfo) {
        this.bizInfo = bizInfo == null ? null : bizInfo.trim();
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column tb_trans_pay_order.env
     *
     * @return the value of tb_trans_pay_order.env
     * @mbg.generated Wed Jan 26 17:49:11 CST 2022
     */
    public Integer getEnv() {
        return env;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column tb_trans_pay_order.env
     *
     * @param env the value for tb_trans_pay_order.env
     * @mbg.generated Wed Jan 26 17:49:11 CST 2022
     */
    public void setEnv(Integer env) {
        this.env = env;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table tb_trans_pay_order
     *
     * @mbg.generated Wed Jan 26 17:49:11 CST 2022
     */
    @Override
    public boolean equals(Object that) {
        if (this == that) {
            return true;
        }
        if (that == null) {
            return false;
        }
        if (getClass() != that.getClass()) {
            return false;
        }
        TransPayOrderPo other = (TransPayOrderPo) that;
        return (this.getId() == null ? other.getId() == null : this.getId().equals(other.getId()))
                && (this.getGmtCreated() == null ? other.getGmtCreated() == null
                : this.getGmtCreated().equals(other.getGmtCreated()))
                && (this.getGmtModified() == null ? other.getGmtModified() == null
                : this.getGmtModified().equals(other.getGmtModified()))
                && (this.getPayOrderNo() == null ? other.getPayOrderNo() == null
                : this.getPayOrderNo().equals(other.getPayOrderNo()))
                && (this.getSysCode() == null ? other.getSysCode() == null
                : this.getSysCode().equals(other.getSysCode()))
                && (this.getBizIdentifyNo() == null ? other.getBizIdentifyNo() == null
                : this.getBizIdentifyNo().equals(other.getBizIdentifyNo()))
                && (this.getBizUniqueNo() == null ? other.getBizUniqueNo() == null
                : this.getBizUniqueNo().equals(other.getBizUniqueNo()))
                && (this.getMoney() == null ? other.getMoney() == null : this.getMoney().equals(other.getMoney()))
                && (this.getPayChannelType() == null ? other.getPayChannelType() == null
                : this.getPayChannelType().equals(other.getPayChannelType()))
                && (this.getTargetAccountType() == null ? other.getTargetAccountType() == null
                : this.getTargetAccountType().equals(other.getTargetAccountType()))
                && (this.getAccountingEntry() == null ? other.getAccountingEntry() == null
                : this.getAccountingEntry().equals(other.getAccountingEntry()))
                && (this.getGmtAcceptedTime() == null ? other.getGmtAcceptedTime() == null
                : this.getGmtAcceptedTime().equals(other.getGmtAcceptedTime()))
                && (this.getGmtPaymentBeginTime() == null ? other.getGmtPaymentBeginTime() == null
                : this.getGmtPaymentBeginTime().equals(other.getGmtPaymentBeginTime()))
                && (this.getGmtPaymentSuccessTime() == null ? other.getGmtPaymentSuccessTime() == null
                : this.getGmtPaymentSuccessTime().equals(other.getGmtPaymentSuccessTime()))
                && (this.getGmtPaymentFailureTime() == null ? other.getGmtPaymentFailureTime() == null
                : this.getGmtPaymentFailureTime().equals(other.getGmtPaymentFailureTime()))
                && (this.getGmtPaymentClosedTime() == null ? other.getGmtPaymentClosedTime() == null
                : this.getGmtPaymentClosedTime().equals(other.getGmtPaymentClosedTime()))
                && (this.getGmtPaymentBouncedTime() == null ? other.getGmtPaymentBouncedTime() == null
                : this.getGmtPaymentBouncedTime().equals(other.getGmtPaymentBouncedTime()))
                && (this.getStatus() == null ? other.getStatus() == null : this.getStatus().equals(other.getStatus()))
                && (this.getVersion() == null ? other.getVersion() == null
                : this.getVersion().equals(other.getVersion()))
                && (this.getMemo() == null ? other.getMemo() == null : this.getMemo().equals(other.getMemo()))
                && (this.getChannelPaymentTraceNo() == null ? other.getChannelPaymentTraceNo() == null
                : this.getChannelPaymentTraceNo().equals(other.getChannelPaymentTraceNo()))
                && (this.getChannelDishonorTraceNo() == null ? other.getChannelDishonorTraceNo() == null
                : this.getChannelDishonorTraceNo().equals(other.getChannelDishonorTraceNo()))
                && (this.getChannelErrorCode() == null ? other.getChannelErrorCode() == null
                : this.getChannelErrorCode().equals(other.getChannelErrorCode()))
                && (this.getBusinessEntity() == null ? other.getBusinessEntity() == null
                : this.getBusinessEntity().equals(other.getBusinessEntity()))
                && (this.getNotifyUri() == null ? other.getNotifyUri() == null
                : this.getNotifyUri().equals(other.getNotifyUri()))
                && (this.getExtendInfo() == null ? other.getExtendInfo() == null
                : this.getExtendInfo().equals(other.getExtendInfo()))
                && (this.getBizInfo() == null ? other.getBizInfo() == null
                : this.getBizInfo().equals(other.getBizInfo()))
                && (this.getEnv() == null ? other.getEnv() == null : this.getEnv().equals(other.getEnv()));
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table tb_trans_pay_order
     *
     * @mbg.generated Wed Jan 26 17:49:11 CST 2022
     */
    @Override
    public int hashCode() {
        final int prime = 31;
        int result = 1;
        result = prime * result + ((getId() == null) ? 0 : getId().hashCode());
        result = prime * result + ((getGmtCreated() == null) ? 0 : getGmtCreated().hashCode());
        result = prime * result + ((getGmtModified() == null) ? 0 : getGmtModified().hashCode());
        result = prime * result + ((getPayOrderNo() == null) ? 0 : getPayOrderNo().hashCode());
        result = prime * result + ((getSysCode() == null) ? 0 : getSysCode().hashCode());
        result = prime * result + ((getBizIdentifyNo() == null) ? 0 : getBizIdentifyNo().hashCode());
        result = prime * result + ((getBizUniqueNo() == null) ? 0 : getBizUniqueNo().hashCode());
        result = prime * result + ((getMoney() == null) ? 0 : getMoney().hashCode());
        result = prime * result + ((getPayChannelType() == null) ? 0 : getPayChannelType().hashCode());
        result = prime * result + ((getTargetAccountType() == null) ? 0 : getTargetAccountType().hashCode());
        result = prime * result + ((getAccountingEntry() == null) ? 0 : getAccountingEntry().hashCode());
        result = prime * result + ((getGmtAcceptedTime() == null) ? 0 : getGmtAcceptedTime().hashCode());
        result = prime * result + ((getGmtPaymentBeginTime() == null) ? 0 : getGmtPaymentBeginTime().hashCode());
        result = prime * result + ((getGmtPaymentSuccessTime() == null) ? 0 : getGmtPaymentSuccessTime().hashCode());
        result = prime * result + ((getGmtPaymentFailureTime() == null) ? 0 : getGmtPaymentFailureTime().hashCode());
        result = prime * result + ((getGmtPaymentClosedTime() == null) ? 0 : getGmtPaymentClosedTime().hashCode());
        result = prime * result + ((getGmtPaymentBouncedTime() == null) ? 0 : getGmtPaymentBouncedTime().hashCode());
        result = prime * result + ((getStatus() == null) ? 0 : getStatus().hashCode());
        result = prime * result + ((getVersion() == null) ? 0 : getVersion().hashCode());
        result = prime * result + ((getMemo() == null) ? 0 : getMemo().hashCode());
        result = prime * result + ((getChannelPaymentTraceNo() == null) ? 0 : getChannelPaymentTraceNo().hashCode());
        result = prime * result + ((getChannelDishonorTraceNo() == null) ? 0 : getChannelDishonorTraceNo().hashCode());
        result = prime * result + ((getChannelErrorCode() == null) ? 0 : getChannelErrorCode().hashCode());
        result = prime * result + ((getBusinessEntity() == null) ? 0 : getBusinessEntity().hashCode());
        result = prime * result + ((getNotifyUri() == null) ? 0 : getNotifyUri().hashCode());
        result = prime * result + ((getExtendInfo() == null) ? 0 : getExtendInfo().hashCode());
        result = prime * result + ((getBizInfo() == null) ? 0 : getBizInfo().hashCode());
        result = prime * result + ((getEnv() == null) ? 0 : getEnv().hashCode());
        return result;
    }
}