package com.magicliang.transaction.sys.common.dal.mybatis.po;

import java.util.Date;

/**
 * This class was generated by MyBatis Generator.
 * This class corresponds to the database table tb_trans_channel_request
 */
public class TransChannelRequestPo {
    /**
     * Database Column Remarks:
     * 自增物理主键，单表唯一
     * <p>
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column tb_trans_channel_request.id
     *
     * @mbg.generated Wed Jan 26 17:49:11 CST 2022
     */
    private Long id;

    /**
     * Database Column Remarks:
     * 创建时间
     * <p>
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column tb_trans_channel_request.gmt_created
     *
     * @mbg.generated Wed Jan 26 17:49:11 CST 2022
     */
    private Date gmtCreated;

    /**
     * Database Column Remarks:
     * 最后修改时间
     * <p>
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column tb_trans_channel_request.gmt_modified
     *
     * @mbg.generated Wed Jan 26 17:49:11 CST 2022
     */
    private Date gmtModified;

    /**
     * Database Column Remarks:
     * 引用 tb_trans_pay_order 支付订单号，业务主键，全局唯一
     * <p>
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column tb_trans_channel_request.pay_order_no
     *
     * @mbg.generated Wed Jan 26 17:49:11 CST 2022
     */
    private Long payOrderNo;

    /**
     * Database Column Remarks:
     * 请求类型
     * <p>
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column tb_trans_channel_request.request_type
     *
     * @mbg.generated Wed Jan 26 17:49:11 CST 2022
     */
    private Integer requestType;

    /**
     * Database Column Remarks:
     * 业务标识码
     * <p>
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column tb_trans_channel_request.biz_identify_no
     *
     * @mbg.generated Wed Jan 26 17:49:11 CST 2022
     */
    private String bizIdentifyNo;

    /**
     * Database Column Remarks:
     * 上游业务号，语义同 out_biz_no，与业务标识码联合后，必须全局唯一，可以作为分表键
     * <p>
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column tb_trans_channel_request.biz_unique_no
     *
     * @mbg.generated Wed Jan 26 17:49:11 CST 2022
     */
    private String bizUniqueNo;

    /**
     * Database Column Remarks:
     * 下次预定执行时间，任务的优先级调度逻辑会间接影响这一列，任务调度框架主要理解这一列
     * <p>
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column tb_trans_channel_request.gmt_next_execution
     *
     * @mbg.generated Wed Jan 26 17:49:11 CST 2022
     */
    private Date gmtNextExecution;

    /**
     * Database Column Remarks:
     * 调用次数
     * <p>
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column tb_trans_channel_request.retry_count
     *
     * @mbg.generated Wed Jan 26 17:49:11 CST 2022
     */
    private Long retryCount;

    /**
     * Database Column Remarks:
     * 请求地址
     * <p>
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column tb_trans_channel_request.request_addr
     *
     * @mbg.generated Wed Jan 26 17:49:11 CST 2022
     */
    private String requestAddr;

    /**
     * Database Column Remarks:
     * 支付状态，1 初始化 2 请求中 3 请求成功 4 请求失败 5请求被关闭
     * <p>
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column tb_trans_channel_request.status
     *
     * @mbg.generated Wed Jan 26 17:49:11 CST 2022
     */
    private Integer status;

    /**
     * Database Column Remarks:
     * 请求被关闭的原因
     * <p>
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column tb_trans_channel_request.close_reason
     *
     * @mbg.generated Wed Jan 26 17:49:11 CST 2022
     */
    private Integer closeReason;

    /**
     * Database Column Remarks:
     * 上次执行时间
     * <p>
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column tb_trans_channel_request.gmt_last_execution
     *
     * @mbg.generated Wed Jan 26 17:49:11 CST 2022
     */
    private Date gmtLastExecution;

    /**
     * Database Column Remarks:
     * 环境，1 dev 2 test 3 staging 4 prod
     * <p>
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column tb_trans_channel_request.env
     *
     * @mbg.generated Wed Jan 26 17:49:11 CST 2022
     */
    private Integer env;

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column tb_trans_channel_request.id
     *
     * @return the value of tb_trans_channel_request.id
     * @mbg.generated Wed Jan 26 17:49:11 CST 2022
     */
    public Long getId() {
        return id;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column tb_trans_channel_request.id
     *
     * @param id the value for tb_trans_channel_request.id
     * @mbg.generated Wed Jan 26 17:49:11 CST 2022
     */
    public void setId(Long id) {
        this.id = id;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column tb_trans_channel_request.gmt_created
     *
     * @return the value of tb_trans_channel_request.gmt_created
     * @mbg.generated Wed Jan 26 17:49:11 CST 2022
     */
    public Date getGmtCreated() {
        return gmtCreated;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column tb_trans_channel_request.gmt_created
     *
     * @param gmtCreated the value for tb_trans_channel_request.gmt_created
     * @mbg.generated Wed Jan 26 17:49:11 CST 2022
     */
    public void setGmtCreated(Date gmtCreated) {
        this.gmtCreated = gmtCreated;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column tb_trans_channel_request.gmt_modified
     *
     * @return the value of tb_trans_channel_request.gmt_modified
     * @mbg.generated Wed Jan 26 17:49:11 CST 2022
     */
    public Date getGmtModified() {
        return gmtModified;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column tb_trans_channel_request.gmt_modified
     *
     * @param gmtModified the value for tb_trans_channel_request.gmt_modified
     * @mbg.generated Wed Jan 26 17:49:11 CST 2022
     */
    public void setGmtModified(Date gmtModified) {
        this.gmtModified = gmtModified;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column tb_trans_channel_request.pay_order_no
     *
     * @return the value of tb_trans_channel_request.pay_order_no
     * @mbg.generated Wed Jan 26 17:49:11 CST 2022
     */
    public Long getPayOrderNo() {
        return payOrderNo;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column tb_trans_channel_request.pay_order_no
     *
     * @param payOrderNo the value for tb_trans_channel_request.pay_order_no
     * @mbg.generated Wed Jan 26 17:49:11 CST 2022
     */
    public void setPayOrderNo(Long payOrderNo) {
        this.payOrderNo = payOrderNo;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column tb_trans_channel_request.request_type
     *
     * @return the value of tb_trans_channel_request.request_type
     * @mbg.generated Wed Jan 26 17:49:11 CST 2022
     */
    public Integer getRequestType() {
        return requestType;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column tb_trans_channel_request.request_type
     *
     * @param requestType the value for tb_trans_channel_request.request_type
     * @mbg.generated Wed Jan 26 17:49:11 CST 2022
     */
    public void setRequestType(Integer requestType) {
        this.requestType = requestType;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column tb_trans_channel_request.biz_identify_no
     *
     * @return the value of tb_trans_channel_request.biz_identify_no
     * @mbg.generated Wed Jan 26 17:49:11 CST 2022
     */
    public String getBizIdentifyNo() {
        return bizIdentifyNo;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column tb_trans_channel_request.biz_identify_no
     *
     * @param bizIdentifyNo the value for tb_trans_channel_request.biz_identify_no
     * @mbg.generated Wed Jan 26 17:49:11 CST 2022
     */
    public void setBizIdentifyNo(String bizIdentifyNo) {
        this.bizIdentifyNo = bizIdentifyNo == null ? null : bizIdentifyNo.trim();
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column tb_trans_channel_request.biz_unique_no
     *
     * @return the value of tb_trans_channel_request.biz_unique_no
     * @mbg.generated Wed Jan 26 17:49:11 CST 2022
     */
    public String getBizUniqueNo() {
        return bizUniqueNo;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column tb_trans_channel_request.biz_unique_no
     *
     * @param bizUniqueNo the value for tb_trans_channel_request.biz_unique_no
     * @mbg.generated Wed Jan 26 17:49:11 CST 2022
     */
    public void setBizUniqueNo(String bizUniqueNo) {
        this.bizUniqueNo = bizUniqueNo == null ? null : bizUniqueNo.trim();
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column tb_trans_channel_request.gmt_next_execution
     *
     * @return the value of tb_trans_channel_request.gmt_next_execution
     * @mbg.generated Wed Jan 26 17:49:11 CST 2022
     */
    public Date getGmtNextExecution() {
        return gmtNextExecution;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column tb_trans_channel_request.gmt_next_execution
     *
     * @param gmtNextExecution the value for tb_trans_channel_request.gmt_next_execution
     * @mbg.generated Wed Jan 26 17:49:11 CST 2022
     */
    public void setGmtNextExecution(Date gmtNextExecution) {
        this.gmtNextExecution = gmtNextExecution;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column tb_trans_channel_request.retry_count
     *
     * @return the value of tb_trans_channel_request.retry_count
     * @mbg.generated Wed Jan 26 17:49:11 CST 2022
     */
    public Long getRetryCount() {
        return retryCount;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column tb_trans_channel_request.retry_count
     *
     * @param retryCount the value for tb_trans_channel_request.retry_count
     * @mbg.generated Wed Jan 26 17:49:11 CST 2022
     */
    public void setRetryCount(Long retryCount) {
        this.retryCount = retryCount;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column tb_trans_channel_request.request_addr
     *
     * @return the value of tb_trans_channel_request.request_addr
     * @mbg.generated Wed Jan 26 17:49:11 CST 2022
     */
    public String getRequestAddr() {
        return requestAddr;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column tb_trans_channel_request.request_addr
     *
     * @param requestAddr the value for tb_trans_channel_request.request_addr
     * @mbg.generated Wed Jan 26 17:49:11 CST 2022
     */
    public void setRequestAddr(String requestAddr) {
        this.requestAddr = requestAddr == null ? null : requestAddr.trim();
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column tb_trans_channel_request.status
     *
     * @return the value of tb_trans_channel_request.status
     * @mbg.generated Wed Jan 26 17:49:11 CST 2022
     */
    public Integer getStatus() {
        return status;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column tb_trans_channel_request.status
     *
     * @param status the value for tb_trans_channel_request.status
     * @mbg.generated Wed Jan 26 17:49:11 CST 2022
     */
    public void setStatus(Integer status) {
        this.status = status;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column tb_trans_channel_request.close_reason
     *
     * @return the value of tb_trans_channel_request.close_reason
     * @mbg.generated Wed Jan 26 17:49:11 CST 2022
     */
    public Integer getCloseReason() {
        return closeReason;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column tb_trans_channel_request.close_reason
     *
     * @param closeReason the value for tb_trans_channel_request.close_reason
     * @mbg.generated Wed Jan 26 17:49:11 CST 2022
     */
    public void setCloseReason(Integer closeReason) {
        this.closeReason = closeReason;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column tb_trans_channel_request.gmt_last_execution
     *
     * @return the value of tb_trans_channel_request.gmt_last_execution
     * @mbg.generated Wed Jan 26 17:49:11 CST 2022
     */
    public Date getGmtLastExecution() {
        return gmtLastExecution;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column tb_trans_channel_request.gmt_last_execution
     *
     * @param gmtLastExecution the value for tb_trans_channel_request.gmt_last_execution
     * @mbg.generated Wed Jan 26 17:49:11 CST 2022
     */
    public void setGmtLastExecution(Date gmtLastExecution) {
        this.gmtLastExecution = gmtLastExecution;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column tb_trans_channel_request.env
     *
     * @return the value of tb_trans_channel_request.env
     * @mbg.generated Wed Jan 26 17:49:11 CST 2022
     */
    public Integer getEnv() {
        return env;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column tb_trans_channel_request.env
     *
     * @param env the value for tb_trans_channel_request.env
     * @mbg.generated Wed Jan 26 17:49:11 CST 2022
     */
    public void setEnv(Integer env) {
        this.env = env;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table tb_trans_channel_request
     *
     * @mbg.generated Wed Jan 26 17:49:11 CST 2022
     */
    @Override
    public boolean equals(Object that) {
        if (this == that) {
            return true;
        }
        if (that == null) {
            return false;
        }
        if (getClass() != that.getClass()) {
            return false;
        }
        TransChannelRequestPo other = (TransChannelRequestPo) that;
        return (this.getId() == null ? other.getId() == null : this.getId().equals(other.getId()))
                && (this.getGmtCreated() == null ? other.getGmtCreated() == null : this.getGmtCreated().equals(other.getGmtCreated()))
                && (this.getGmtModified() == null ? other.getGmtModified() == null : this.getGmtModified().equals(other.getGmtModified()))
                && (this.getPayOrderNo() == null ? other.getPayOrderNo() == null : this.getPayOrderNo().equals(other.getPayOrderNo()))
                && (this.getRequestType() == null ? other.getRequestType() == null : this.getRequestType().equals(other.getRequestType()))
                && (this.getBizIdentifyNo() == null ? other.getBizIdentifyNo() == null : this.getBizIdentifyNo().equals(other.getBizIdentifyNo()))
                && (this.getBizUniqueNo() == null ? other.getBizUniqueNo() == null : this.getBizUniqueNo().equals(other.getBizUniqueNo()))
                && (this.getGmtNextExecution() == null ? other.getGmtNextExecution() == null : this.getGmtNextExecution().equals(other.getGmtNextExecution()))
                && (this.getRetryCount() == null ? other.getRetryCount() == null : this.getRetryCount().equals(other.getRetryCount()))
                && (this.getRequestAddr() == null ? other.getRequestAddr() == null : this.getRequestAddr().equals(other.getRequestAddr()))
                && (this.getStatus() == null ? other.getStatus() == null : this.getStatus().equals(other.getStatus()))
                && (this.getCloseReason() == null ? other.getCloseReason() == null : this.getCloseReason().equals(other.getCloseReason()))
                && (this.getGmtLastExecution() == null ? other.getGmtLastExecution() == null : this.getGmtLastExecution().equals(other.getGmtLastExecution()))
                && (this.getEnv() == null ? other.getEnv() == null : this.getEnv().equals(other.getEnv()));
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table tb_trans_channel_request
     *
     * @mbg.generated Wed Jan 26 17:49:11 CST 2022
     */
    @Override
    public int hashCode() {
        final int prime = 31;
        int result = 1;
        result = prime * result + ((getId() == null) ? 0 : getId().hashCode());
        result = prime * result + ((getGmtCreated() == null) ? 0 : getGmtCreated().hashCode());
        result = prime * result + ((getGmtModified() == null) ? 0 : getGmtModified().hashCode());
        result = prime * result + ((getPayOrderNo() == null) ? 0 : getPayOrderNo().hashCode());
        result = prime * result + ((getRequestType() == null) ? 0 : getRequestType().hashCode());
        result = prime * result + ((getBizIdentifyNo() == null) ? 0 : getBizIdentifyNo().hashCode());
        result = prime * result + ((getBizUniqueNo() == null) ? 0 : getBizUniqueNo().hashCode());
        result = prime * result + ((getGmtNextExecution() == null) ? 0 : getGmtNextExecution().hashCode());
        result = prime * result + ((getRetryCount() == null) ? 0 : getRetryCount().hashCode());
        result = prime * result + ((getRequestAddr() == null) ? 0 : getRequestAddr().hashCode());
        result = prime * result + ((getStatus() == null) ? 0 : getStatus().hashCode());
        result = prime * result + ((getCloseReason() == null) ? 0 : getCloseReason().hashCode());
        result = prime * result + ((getGmtLastExecution() == null) ? 0 : getGmtLastExecution().hashCode());
        result = prime * result + ((getEnv() == null) ? 0 : getEnv().hashCode());
        return result;
    }
}