package com.magicliang.transaction.sys.common.dal.mybatis.po;

/**
 * This class was generated by MyBatis Generator.
 * This class corresponds to the database table tb_trans_channel_request
 */
public class TransChannelRequestPoWithBLOBs extends TransChannelRequestPo {
    /**
     * Database Column Remarks:
     * 请求参数
     * <p>
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column tb_trans_channel_request.request_params
     *
     * @mbg.generated Wed Jan 26 17:49:11 CST 2022
     */
    private String requestParams;

    /**
     * Database Column Remarks:
     * 请求响应
     * <p>
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column tb_trans_channel_request.request_response
     *
     * @mbg.generated Wed Jan 26 17:49:11 CST 2022
     */
    private String requestResponse;

    /**
     * Database Column Remarks:
     * 回调参数
     * <p>
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column tb_trans_channel_request.callback_params
     *
     * @mbg.generated Wed Jan 26 17:49:11 CST 2022
     */
    private String callbackParams;

    /**
     * Database Column Remarks:
     * 请求异常
     * <p>
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column tb_trans_channel_request.request_exception
     *
     * @mbg.generated Wed Jan 26 17:49:11 CST 2022
     */
    private String requestException;

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column tb_trans_channel_request.request_params
     *
     * @return the value of tb_trans_channel_request.request_params
     * @mbg.generated Wed Jan 26 17:49:11 CST 2022
     */
    public String getRequestParams() {
        return requestParams;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column tb_trans_channel_request.request_params
     *
     * @param requestParams the value for tb_trans_channel_request.request_params
     * @mbg.generated Wed Jan 26 17:49:11 CST 2022
     */
    public void setRequestParams(String requestParams) {
        this.requestParams = requestParams == null ? null : requestParams.trim();
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column tb_trans_channel_request.request_response
     *
     * @return the value of tb_trans_channel_request.request_response
     * @mbg.generated Wed Jan 26 17:49:11 CST 2022
     */
    public String getRequestResponse() {
        return requestResponse;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column tb_trans_channel_request.request_response
     *
     * @param requestResponse the value for tb_trans_channel_request.request_response
     * @mbg.generated Wed Jan 26 17:49:11 CST 2022
     */
    public void setRequestResponse(String requestResponse) {
        this.requestResponse = requestResponse == null ? null : requestResponse.trim();
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column tb_trans_channel_request.callback_params
     *
     * @return the value of tb_trans_channel_request.callback_params
     * @mbg.generated Wed Jan 26 17:49:11 CST 2022
     */
    public String getCallbackParams() {
        return callbackParams;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column tb_trans_channel_request.callback_params
     *
     * @param callbackParams the value for tb_trans_channel_request.callback_params
     * @mbg.generated Wed Jan 26 17:49:11 CST 2022
     */
    public void setCallbackParams(String callbackParams) {
        this.callbackParams = callbackParams == null ? null : callbackParams.trim();
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column tb_trans_channel_request.request_exception
     *
     * @return the value of tb_trans_channel_request.request_exception
     * @mbg.generated Wed Jan 26 17:49:11 CST 2022
     */
    public String getRequestException() {
        return requestException;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column tb_trans_channel_request.request_exception
     *
     * @param requestException the value for tb_trans_channel_request.request_exception
     * @mbg.generated Wed Jan 26 17:49:11 CST 2022
     */
    public void setRequestException(String requestException) {
        this.requestException = requestException == null ? null : requestException.trim();
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table tb_trans_channel_request
     *
     * @mbg.generated Wed Jan 26 17:49:11 CST 2022
     */
    @Override
    public boolean equals(Object that) {
        if (this == that) {
            return true;
        }
        if (that == null) {
            return false;
        }
        if (getClass() != that.getClass()) {
            return false;
        }
        TransChannelRequestPoWithBLOBs other = (TransChannelRequestPoWithBLOBs) that;
        return (this.getId() == null ? other.getId() == null : this.getId().equals(other.getId()))
                && (this.getGmtCreated() == null ? other.getGmtCreated() == null : this.getGmtCreated().equals(other.getGmtCreated()))
                && (this.getGmtModified() == null ? other.getGmtModified() == null : this.getGmtModified().equals(other.getGmtModified()))
                && (this.getPayOrderNo() == null ? other.getPayOrderNo() == null : this.getPayOrderNo().equals(other.getPayOrderNo()))
                && (this.getRequestType() == null ? other.getRequestType() == null : this.getRequestType().equals(other.getRequestType()))
                && (this.getBizIdentifyNo() == null ? other.getBizIdentifyNo() == null : this.getBizIdentifyNo().equals(other.getBizIdentifyNo()))
                && (this.getBizUniqueNo() == null ? other.getBizUniqueNo() == null : this.getBizUniqueNo().equals(other.getBizUniqueNo()))
                && (this.getGmtNextExecution() == null ? other.getGmtNextExecution() == null : this.getGmtNextExecution().equals(other.getGmtNextExecution()))
                && (this.getRetryCount() == null ? other.getRetryCount() == null : this.getRetryCount().equals(other.getRetryCount()))
                && (this.getRequestAddr() == null ? other.getRequestAddr() == null : this.getRequestAddr().equals(other.getRequestAddr()))
                && (this.getStatus() == null ? other.getStatus() == null : this.getStatus().equals(other.getStatus()))
                && (this.getCloseReason() == null ? other.getCloseReason() == null : this.getCloseReason().equals(other.getCloseReason()))
                && (this.getGmtLastExecution() == null ? other.getGmtLastExecution() == null : this.getGmtLastExecution().equals(other.getGmtLastExecution()))
                && (this.getEnv() == null ? other.getEnv() == null : this.getEnv().equals(other.getEnv()))
                && (this.getRequestParams() == null ? other.getRequestParams() == null : this.getRequestParams().equals(other.getRequestParams()))
                && (this.getRequestResponse() == null ? other.getRequestResponse() == null : this.getRequestResponse().equals(other.getRequestResponse()))
                && (this.getCallbackParams() == null ? other.getCallbackParams() == null : this.getCallbackParams().equals(other.getCallbackParams()))
                && (this.getRequestException() == null ? other.getRequestException() == null : this.getRequestException().equals(other.getRequestException()));
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table tb_trans_channel_request
     *
     * @mbg.generated Wed Jan 26 17:49:11 CST 2022
     */
    @Override
    public int hashCode() {
        final int prime = 31;
        int result = 1;
        result = prime * result + ((getId() == null) ? 0 : getId().hashCode());
        result = prime * result + ((getGmtCreated() == null) ? 0 : getGmtCreated().hashCode());
        result = prime * result + ((getGmtModified() == null) ? 0 : getGmtModified().hashCode());
        result = prime * result + ((getPayOrderNo() == null) ? 0 : getPayOrderNo().hashCode());
        result = prime * result + ((getRequestType() == null) ? 0 : getRequestType().hashCode());
        result = prime * result + ((getBizIdentifyNo() == null) ? 0 : getBizIdentifyNo().hashCode());
        result = prime * result + ((getBizUniqueNo() == null) ? 0 : getBizUniqueNo().hashCode());
        result = prime * result + ((getGmtNextExecution() == null) ? 0 : getGmtNextExecution().hashCode());
        result = prime * result + ((getRetryCount() == null) ? 0 : getRetryCount().hashCode());
        result = prime * result + ((getRequestAddr() == null) ? 0 : getRequestAddr().hashCode());
        result = prime * result + ((getStatus() == null) ? 0 : getStatus().hashCode());
        result = prime * result + ((getCloseReason() == null) ? 0 : getCloseReason().hashCode());
        result = prime * result + ((getGmtLastExecution() == null) ? 0 : getGmtLastExecution().hashCode());
        result = prime * result + ((getEnv() == null) ? 0 : getEnv().hashCode());
        result = prime * result + ((getRequestParams() == null) ? 0 : getRequestParams().hashCode());
        result = prime * result + ((getRequestResponse() == null) ? 0 : getRequestResponse().hashCode());
        result = prime * result + ((getCallbackParams() == null) ? 0 : getCallbackParams().hashCode());
        result = prime * result + ((getRequestException() == null) ? 0 : getRequestException().hashCode());
        return result;
    }
}