apiVersion: v1
kind: Service
metadata:
  name: ddts-app-svc
  namespace: ddts-prod
  labels:
    app: ddts-app
    environment: prod
spec:
  type: LoadBalancer
  selector:
    app: ddts-app
  ports:
    - port: 8502
      targetPort: 8502
      protocol: TCP
      name: http
